/* Appearance.h generated by valac 0.56.16, the Vala compiler, do not modify */

#ifndef ___HOME_EM_DESKTOP_CODE_DOCKS_SERVICES_LIBS_APPEARANCE_H__
#define ___HOME_EM_DESKTOP_CODE_DOCKS_SERVICES_LIBS_APPEARANCE_H__

#include <glib.h>

G_BEGIN_DECLS

G_END_DECLS

#endif
