/* Bluetooth.c generated by valac 0.56.16, the Vala compiler
 * generated from Bluetooth.vala, do not modify */

#include <glib-object.h>
#include <gio/gio.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include "Bluetooth.h"
#include <stdio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define TYPE_BLUEZ (bluez_get_type ())
#define BLUEZ(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BLUEZ, Bluez))
#define IS_BLUEZ(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BLUEZ))
#define BLUEZ_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_BLUEZ, BluezIface))

typedef struct _Bluez Bluez;
typedef struct _BluezIface BluezIface;

#define TYPE_BLUEZ_PROXY (bluez_proxy_get_type ())
enum  {
	BLUEZ_DISCOVERY_STARTED_SIGNAL,
	BLUEZ_DISCOVERY_COMPLETED_SIGNAL,
	BLUEZ_REMOTE_DEVICE_FOUND_SIGNAL,
	BLUEZ_REMOTE_NAME_UPDATED_SIGNAL,
	BLUEZ_NUM_SIGNALS
};
static guint bluez_signals[BLUEZ_NUM_SIGNALS] = {0};
typedef GDBusProxy BluezProxy;
typedef GDBusProxyClass BluezProxyClass;
#define _g_free0(var) (var = (g_free (var), NULL))
enum  {
	BLUETOOTH_0_PROPERTY,
	BLUETOOTH_NUM_PROPERTIES
};
static GParamSpec* bluetooth_properties[BLUETOOTH_NUM_PROPERTIES];
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _BluezIface {
	GTypeInterface parent_iface;
	void (*start_discovery) (Bluez* self, GError** error);
	gchar** (*get_discovery_filters) (Bluez* self, gint* result_length1);
	gchar* (*get_address) (Bluez* self);
};

struct _BluetoothPrivate {
	GMainLoop* loop;
};

static gint Bluetooth_private_offset;
static gpointer bluetooth_parent_class = NULL;

VALA_EXTERN GType bluez_proxy_get_type (void) G_GNUC_CONST ;
VALA_EXTERN guint bluez_register_object (void* object,
                             GDBusConnection* connection,
                             const gchar* path,
                             GError** error);
VALA_EXTERN GType bluez_get_type (void) G_GNUC_CONST ;
VALA_EXTERN void bluez_start_discovery (Bluez* self,
                            GError** error);
VALA_EXTERN gchar** bluez_get_discovery_filters (Bluez* self,
                                     gint* result_length1);
VALA_EXTERN gchar* bluez_get_address (Bluez* self);
static void g_cclosure_user_marshal_VOID__STRING_UINT_INT (GClosure * closure,
                                                    GValue * return_value,
                                                    guint n_param_values,
                                                    const GValue * param_values,
                                                    gpointer invocation_hint,
                                                    gpointer marshal_data);
static void g_cclosure_user_marshal_VOID__STRING_STRING (GClosure * closure,
                                                  GValue * return_value,
                                                  guint n_param_values,
                                                  const GValue * param_values,
                                                  gpointer invocation_hint,
                                                  gpointer marshal_data);
static GType bluez_get_type_once (void);
static void bluez_proxy_g_signal (GDBusProxy* proxy,
                           const gchar* sender_name,
                           const gchar* signal_name,
                           GVariant* parameters);
static void _dbus_handle_bluez_discovery_started (Bluez* self,
                                           GVariant* parameters);
static void _dbus_handle_bluez_discovery_completed (Bluez* self,
                                             GVariant* parameters);
static void _dbus_handle_bluez_remote_device_found (Bluez* self,
                                             GVariant* parameters);
static void _dbus_handle_bluez_remote_name_updated (Bluez* self,
                                             GVariant* parameters);
static void bluez_proxy_start_discovery (Bluez* self,
                                  GError** error);
static gchar** bluez_proxy_get_discovery_filters (Bluez* self,
                                           gint* result_length1);
static gchar* bluez_dbus_proxy_get_address (Bluez* self);
static void bluez_proxy_bluez_interface_init (BluezIface* iface);
static void _dbus_bluez_start_discovery (Bluez* self,
                                  GVariant* _parameters_,
                                  GDBusMethodInvocation* invocation);
static void _dbus_bluez_get_discovery_filters (Bluez* self,
                                        GVariant* _parameters_,
                                        GDBusMethodInvocation* invocation);
static void bluez_dbus_interface_method_call (GDBusConnection* connection,
                                       const gchar* sender,
                                       const gchar* object_path,
                                       const gchar* interface_name,
                                       const gchar* method_name,
                                       GVariant* parameters,
                                       GDBusMethodInvocation* invocation,
                                       gpointer user_data);
static GVariant* bluez_dbus_interface_get_property (GDBusConnection* connection,
                                             const gchar* sender,
                                             const gchar* object_path,
                                             const gchar* interface_name,
                                             const gchar* property_name,
                                             GError** error,
                                             gpointer user_data);
static GVariant* _dbus_bluez_get_address (Bluez* self);
static gboolean bluez_dbus_interface_set_property (GDBusConnection* connection,
                                            const gchar* sender,
                                            const gchar* object_path,
                                            const gchar* interface_name,
                                            const gchar* property_name,
                                            GVariant* value,
                                            GError** error,
                                            gpointer user_data);
static void _dbus_bluez_discovery_started (GObject* _sender,
                                    gpointer* _data);
static void _dbus_bluez_discovery_completed (GObject* _sender,
                                      gpointer* _data);
static void _dbus_bluez_remote_device_found (GObject* _sender,
                                      const gchar* address,
                                      guint klass,
                                      gint rssi,
                                      gpointer* _data);
static void _dbus_bluez_remote_name_updated (GObject* _sender,
                                      const gchar* address,
                                      const gchar* name,
                                      gpointer* _data);
static void _bluez_unregister_object (gpointer user_data);
static void bluetooth_on_remote_device_found (Bluetooth* self,
                                       const gchar* address,
                                       guint klass,
                                       gint rssi);
static void bluetooth_on_discovery_started (Bluetooth* self);
static void bluetooth_on_remote_name_updated (Bluetooth* self,
                                       const gchar* address,
                                       const gchar* name);
static void bluetooth_on_discovery_completed (Bluetooth* self);
static void _bluetooth_on_remote_device_found_bluez_remote_device_found (Bluez* _sender,
                                                                  const gchar* address,
                                                                  guint klass,
                                                                  gint rssi,
                                                                  gpointer self);
static void _bluetooth_on_discovery_started_bluez_discovery_started (Bluez* _sender,
                                                              gpointer self);
static void _bluetooth_on_discovery_completed_bluez_discovery_completed (Bluez* _sender,
                                                                  gpointer self);
static void _bluetooth_on_remote_name_updated_bluez_remote_name_updated (Bluez* _sender,
                                                                  const gchar* address,
                                                                  const gchar* name,
                                                                  gpointer self);
static void bluetooth_finalize (GObject * obj);
static GType bluetooth_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

static const GDBusArgInfo * const _bluez_dbus_arg_info_start_discovery_in[] = {NULL};
static const GDBusArgInfo * const _bluez_dbus_arg_info_start_discovery_out[] = {NULL};
static const GDBusMethodInfo _bluez_dbus_method_info_start_discovery = {-1, "StartDiscovery", (GDBusArgInfo **) (&_bluez_dbus_arg_info_start_discovery_in), (GDBusArgInfo **) (&_bluez_dbus_arg_info_start_discovery_out), NULL};
static const GDBusArgInfo _bluez_dbus_arg_info_get_discovery_filters_result = {-1, "result", "as", NULL};
static const GDBusArgInfo * const _bluez_dbus_arg_info_get_discovery_filters_in[] = {NULL};
static const GDBusArgInfo * const _bluez_dbus_arg_info_get_discovery_filters_out[] = {&_bluez_dbus_arg_info_get_discovery_filters_result, NULL};
static const GDBusMethodInfo _bluez_dbus_method_info_get_discovery_filters = {-1, "GetDiscoveryFilters", (GDBusArgInfo **) (&_bluez_dbus_arg_info_get_discovery_filters_in), (GDBusArgInfo **) (&_bluez_dbus_arg_info_get_discovery_filters_out), NULL};
static const GDBusMethodInfo * const _bluez_dbus_method_info[] = {&_bluez_dbus_method_info_start_discovery, &_bluez_dbus_method_info_get_discovery_filters, NULL};
static const GDBusArgInfo * const _bluez_dbus_arg_info_discovery_started[] = {NULL};
static const GDBusSignalInfo _bluez_dbus_signal_info_discovery_started = {-1, "DiscoveryStarted", (GDBusArgInfo **) (&_bluez_dbus_arg_info_discovery_started), NULL};
static const GDBusArgInfo * const _bluez_dbus_arg_info_discovery_completed[] = {NULL};
static const GDBusSignalInfo _bluez_dbus_signal_info_discovery_completed = {-1, "DiscoveryCompleted", (GDBusArgInfo **) (&_bluez_dbus_arg_info_discovery_completed), NULL};
static const GDBusArgInfo _bluez_dbus_arg_info_remote_device_found_address = {-1, "address", "s", NULL};
static const GDBusArgInfo _bluez_dbus_arg_info_remote_device_found_klass = {-1, "klass", "u", NULL};
static const GDBusArgInfo _bluez_dbus_arg_info_remote_device_found_rssi = {-1, "rssi", "i", NULL};
static const GDBusArgInfo * const _bluez_dbus_arg_info_remote_device_found[] = {&_bluez_dbus_arg_info_remote_device_found_address, &_bluez_dbus_arg_info_remote_device_found_klass, &_bluez_dbus_arg_info_remote_device_found_rssi, NULL};
static const GDBusSignalInfo _bluez_dbus_signal_info_remote_device_found = {-1, "RemoteDeviceFound", (GDBusArgInfo **) (&_bluez_dbus_arg_info_remote_device_found), NULL};
static const GDBusArgInfo _bluez_dbus_arg_info_remote_name_updated_address = {-1, "address", "s", NULL};
static const GDBusArgInfo _bluez_dbus_arg_info_remote_name_updated_name = {-1, "name", "s", NULL};
static const GDBusArgInfo * const _bluez_dbus_arg_info_remote_name_updated[] = {&_bluez_dbus_arg_info_remote_name_updated_address, &_bluez_dbus_arg_info_remote_name_updated_name, NULL};
static const GDBusSignalInfo _bluez_dbus_signal_info_remote_name_updated = {-1, "RemoteNameUpdated", (GDBusArgInfo **) (&_bluez_dbus_arg_info_remote_name_updated), NULL};
static const GDBusSignalInfo * const _bluez_dbus_signal_info[] = {&_bluez_dbus_signal_info_discovery_started, &_bluez_dbus_signal_info_discovery_completed, &_bluez_dbus_signal_info_remote_device_found, &_bluez_dbus_signal_info_remote_name_updated, NULL};
static const GDBusPropertyInfo _bluez_dbus_property_info_address = {-1, "Address", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE, NULL};
static const GDBusPropertyInfo * const _bluez_dbus_property_info[] = {&_bluez_dbus_property_info_address, NULL};
static const GDBusInterfaceInfo _bluez_dbus_interface_info = {-1, "org.bluez.Adapter1", (GDBusMethodInfo **) (&_bluez_dbus_method_info), (GDBusSignalInfo **) (&_bluez_dbus_signal_info), (GDBusPropertyInfo **) (&_bluez_dbus_property_info), NULL};
static const GDBusInterfaceVTable _bluez_dbus_interface_vtable = {bluez_dbus_interface_method_call, bluez_dbus_interface_get_property, bluez_dbus_interface_set_property};

void
bluez_start_discovery (Bluez* self,
                       GError** error)
{
	BluezIface* _iface_;
	g_return_if_fail (self != NULL);
	_iface_ = BLUEZ_GET_INTERFACE (self);
	if (_iface_->start_discovery) {
		_iface_->start_discovery (self, error);
	}
}

gchar**
bluez_get_discovery_filters (Bluez* self,
                             gint* result_length1)
{
	BluezIface* _iface_;
	g_return_val_if_fail (self != NULL, NULL);
	_iface_ = BLUEZ_GET_INTERFACE (self);
	if (_iface_->get_discovery_filters) {
		return _iface_->get_discovery_filters (self, result_length1);
	}
	return NULL;
}

gchar*
bluez_get_address (Bluez* self)
{
	BluezIface* _iface_;
	g_return_val_if_fail (self != NULL, NULL);
	_iface_ = BLUEZ_GET_INTERFACE (self);
	if (_iface_->get_address) {
		return _iface_->get_address (self);
	}
	return NULL;
}

static void
g_cclosure_user_marshal_VOID__STRING_UINT_INT (GClosure * closure,
                                               GValue * return_value,
                                               guint n_param_values,
                                               const GValue * param_values,
                                               gpointer invocation_hint,
                                               gpointer marshal_data)
{
	typedef void (*GMarshalFunc_VOID__STRING_UINT_INT) (gpointer data1, const char* arg_1, guint arg_2, gint arg_3, gpointer data2);
	register GMarshalFunc_VOID__STRING_UINT_INT callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 4);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__STRING_UINT_INT) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_string (param_values + 1), g_value_get_uint (param_values + 2), g_value_get_int (param_values + 3), data2);
}

static void
g_cclosure_user_marshal_VOID__STRING_STRING (GClosure * closure,
                                             GValue * return_value,
                                             guint n_param_values,
                                             const GValue * param_values,
                                             gpointer invocation_hint,
                                             gpointer marshal_data)
{
	typedef void (*GMarshalFunc_VOID__STRING_STRING) (gpointer data1, const char* arg_1, const char* arg_2, gpointer data2);
	register GMarshalFunc_VOID__STRING_STRING callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__STRING_STRING) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_string (param_values + 1), g_value_get_string (param_values + 2), data2);
}

static void
bluez_default_init (BluezIface * iface,
                    gpointer iface_data)
{
	bluez_signals[BLUEZ_DISCOVERY_STARTED_SIGNAL] = g_signal_new ("discovery-started", TYPE_BLUEZ, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	bluez_signals[BLUEZ_DISCOVERY_COMPLETED_SIGNAL] = g_signal_new ("discovery-completed", TYPE_BLUEZ, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	bluez_signals[BLUEZ_REMOTE_DEVICE_FOUND_SIGNAL] = g_signal_new ("remote-device-found", TYPE_BLUEZ, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__STRING_UINT_INT, G_TYPE_NONE, 3, G_TYPE_STRING, G_TYPE_UINT, G_TYPE_INT);
	bluez_signals[BLUEZ_REMOTE_NAME_UPDATED_SIGNAL] = g_signal_new ("remote-name-updated", TYPE_BLUEZ, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__STRING_STRING, G_TYPE_NONE, 2, G_TYPE_STRING, G_TYPE_STRING);
}

static GType
bluez_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BluezIface), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bluez_default_init, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
	GType bluez_type_id;
	bluez_type_id = g_type_register_static (G_TYPE_INTERFACE, "Bluez", &g_define_type_info, 0);
	g_type_interface_add_prerequisite (bluez_type_id, G_TYPE_OBJECT);
	g_type_set_qdata (bluez_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) bluez_proxy_get_type);
	g_type_set_qdata (bluez_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.bluez.Adapter1");
	g_type_set_qdata (bluez_type_id, g_quark_from_static_string ("vala-dbus-interface-info"), (void*) (&_bluez_dbus_interface_info));
	g_type_set_qdata (bluez_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) bluez_register_object);
	return bluez_type_id;
}

GType
bluez_get_type (void)
{
	static volatile gsize bluez_type_id__once = 0;
	if (g_once_init_enter (&bluez_type_id__once)) {
		GType bluez_type_id;
		bluez_type_id = bluez_get_type_once ();
		g_once_init_leave (&bluez_type_id__once, bluez_type_id);
	}
	return bluez_type_id__once;
}

G_DEFINE_TYPE_EXTENDED (BluezProxy, bluez_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_BLUEZ, bluez_proxy_bluez_interface_init) )
static void
bluez_proxy_class_init (BluezProxyClass* klass)
{
	G_DBUS_PROXY_CLASS (klass)->g_signal = bluez_proxy_g_signal;
}

static void
_dbus_handle_bluez_discovery_started (Bluez* self,
                                      GVariant* parameters)
{
	GVariantIter _arguments_iter;
	g_variant_iter_init (&_arguments_iter, parameters);
	g_signal_emit_by_name (self, "discovery-started");
}

static void
_dbus_handle_bluez_discovery_completed (Bluez* self,
                                        GVariant* parameters)
{
	GVariantIter _arguments_iter;
	g_variant_iter_init (&_arguments_iter, parameters);
	g_signal_emit_by_name (self, "discovery-completed");
}

static void
_dbus_handle_bluez_remote_device_found (Bluez* self,
                                        GVariant* parameters)
{
	GVariantIter _arguments_iter;
	gchar* address = NULL;
	GVariant* _tmp0_;
	guint klass = 0U;
	GVariant* _tmp1_;
	gint rssi = 0;
	GVariant* _tmp2_;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp0_ = g_variant_iter_next_value (&_arguments_iter);
	address = g_variant_dup_string (_tmp0_, NULL);
	g_variant_unref (_tmp0_);
	_tmp1_ = g_variant_iter_next_value (&_arguments_iter);
	klass = g_variant_get_uint32 (_tmp1_);
	g_variant_unref (_tmp1_);
	_tmp2_ = g_variant_iter_next_value (&_arguments_iter);
	rssi = g_variant_get_int32 (_tmp2_);
	g_variant_unref (_tmp2_);
	g_signal_emit_by_name (self, "remote-device-found", address, klass, rssi);
	_g_free0 (address);
}

static void
_dbus_handle_bluez_remote_name_updated (Bluez* self,
                                        GVariant* parameters)
{
	GVariantIter _arguments_iter;
	gchar* address = NULL;
	GVariant* _tmp3_;
	gchar* name = NULL;
	GVariant* _tmp4_;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp3_ = g_variant_iter_next_value (&_arguments_iter);
	address = g_variant_dup_string (_tmp3_, NULL);
	g_variant_unref (_tmp3_);
	_tmp4_ = g_variant_iter_next_value (&_arguments_iter);
	name = g_variant_dup_string (_tmp4_, NULL);
	g_variant_unref (_tmp4_);
	g_signal_emit_by_name (self, "remote-name-updated", address, name);
	_g_free0 (address);
	_g_free0 (name);
}

static void
bluez_proxy_g_signal (GDBusProxy* proxy,
                      const gchar* sender_name,
                      const gchar* signal_name,
                      GVariant* parameters)
{
	if (strcmp (signal_name, "DiscoveryStarted") == 0) {
		_dbus_handle_bluez_discovery_started ((Bluez*) proxy, parameters);
	} else if (strcmp (signal_name, "DiscoveryCompleted") == 0) {
		_dbus_handle_bluez_discovery_completed ((Bluez*) proxy, parameters);
	} else if (strcmp (signal_name, "RemoteDeviceFound") == 0) {
		_dbus_handle_bluez_remote_device_found ((Bluez*) proxy, parameters);
	} else if (strcmp (signal_name, "RemoteNameUpdated") == 0) {
		_dbus_handle_bluez_remote_name_updated ((Bluez*) proxy, parameters);
	}
}

static void
bluez_proxy_init (BluezProxy* self)
{
	g_dbus_proxy_set_interface_info (G_DBUS_PROXY (self), (GDBusInterfaceInfo *) (&_bluez_dbus_interface_info));
}

static void
bluez_proxy_start_discovery (Bluez* self,
                             GError** error)
{
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.bluez.Adapter1", "StartDiscovery");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}

static gchar**
bluez_proxy_get_discovery_filters (Bluez* self,
                                   gint* result_length1)
{
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gchar** _result = NULL;
	gint _result_length1;
	GVariant* _tmp5_;
	gchar** _tmp6_;
	gint _tmp6__length;
	gint _tmp6__size;
	gint _tmp6__length1;
	GVariantIter _tmp7_;
	GVariant* _tmp8_;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.bluez.Adapter1", "GetDiscoveryFilters");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, NULL);
	g_object_unref (_message);
	if (!_reply_message) {
		return NULL;
	}
	if (g_dbus_message_to_gerror (_reply_message, NULL)) {
		g_object_unref (_reply_message);
		return NULL;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_result_length1 = 0;
	_tmp5_ = g_variant_iter_next_value (&_reply_iter);
	_tmp6_ = g_new (gchar*, 5);
	_tmp6__length = 0;
	_tmp6__size = 4;
	_tmp6__length1 = 0;
	g_variant_iter_init (&_tmp7_, _tmp5_);
	for (; (_tmp8_ = g_variant_iter_next_value (&_tmp7_)) != NULL; _tmp6__length1++) {
		if (_tmp6__size == _tmp6__length) {
			_tmp6__size = 2 * _tmp6__size;
			_tmp6_ = g_renew (gchar*, _tmp6_, _tmp6__size + 1);
		}
		_tmp6_[_tmp6__length++] = g_variant_dup_string (_tmp8_, NULL);
		g_variant_unref (_tmp8_);
	}
	_result_length1 = _tmp6__length1;
	_tmp6_[_tmp6__length] = NULL;
	_result = _tmp6_;
	g_variant_unref (_tmp5_);
	*result_length1 = _result_length1;
	g_object_unref (_reply_message);
	return _result;
}

static gchar*
bluez_dbus_proxy_get_address (Bluez* self)
{
	GVariant *_inner_reply;
	gchar* _result;
	_inner_reply = g_dbus_proxy_get_cached_property ((GDBusProxy *) self, "Address");
	if (!_inner_reply) {
		GVariant *_arguments;
		GVariant *_reply;
		GVariantBuilder _arguments_builder;
		g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
		g_variant_builder_add_value (&_arguments_builder, g_variant_new_string ("org.bluez.Adapter1"));
		g_variant_builder_add_value (&_arguments_builder, g_variant_new_string ("Address"));
		_arguments = g_variant_builder_end (&_arguments_builder);
		_reply = g_dbus_proxy_call_sync ((GDBusProxy *) self, "org.freedesktop.DBus.Properties.Get", _arguments, G_DBUS_CALL_FLAGS_NONE, -1, NULL, NULL);
		if (!_reply) {
			return NULL;
		}
		g_variant_get (_reply, "(v)", &_inner_reply);
		g_variant_unref (_reply);
	}
	_result = g_variant_dup_string (_inner_reply, NULL);
	g_variant_unref (_inner_reply);
	return _result;
}

static void
bluez_proxy_bluez_interface_init (BluezIface* iface)
{
	iface->start_discovery = bluez_proxy_start_discovery;
	iface->get_discovery_filters = bluez_proxy_get_discovery_filters;
	iface->get_address = bluez_dbus_proxy_get_address;
}

static void
_dbus_bluez_start_discovery (Bluez* self,
                             GVariant* _parameters_,
                             GDBusMethodInvocation* invocation)
{
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message = NULL;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	bluez_start_discovery (self, &error);
	if (error) {
		g_dbus_method_invocation_take_error (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}

static void
_dbus_bluez_get_discovery_filters (Bluez* self,
                                   GVariant* _parameters_,
                                   GDBusMethodInvocation* invocation)
{
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message = NULL;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gchar** result;
	gint result_length1 = 0;
	gchar** _tmp9_;
	GVariantBuilder _tmp10_;
	gint _tmp11_;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	result = bluez_get_discovery_filters (self, &result_length1);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_tmp9_ = result;
	g_variant_builder_init (&_tmp10_, G_VARIANT_TYPE ("as"));
	for (_tmp11_ = 0; _tmp11_ < result_length1; _tmp11_++) {
		g_variant_builder_add_value (&_tmp10_, g_variant_new_string (*_tmp9_));
		_tmp9_++;
	}
	g_variant_builder_add_value (&_reply_builder, g_variant_builder_end (&_tmp10_));
	result = (_vala_array_free (result, result_length1, (GDestroyNotify) g_free), NULL);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}

static void
bluez_dbus_interface_method_call (GDBusConnection* connection,
                                  const gchar* sender,
                                  const gchar* object_path,
                                  const gchar* interface_name,
                                  const gchar* method_name,
                                  GVariant* parameters,
                                  GDBusMethodInvocation* invocation,
                                  gpointer user_data)
{
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "StartDiscovery") == 0) {
		_dbus_bluez_start_discovery (object, parameters, invocation);
	} else if (strcmp (method_name, "GetDiscoveryFilters") == 0) {
		_dbus_bluez_get_discovery_filters (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}

static GVariant*
_dbus_bluez_get_address (Bluez* self)
{
	gchar* result;
	GVariant* _reply;
	result = bluez_get_address (self);
	_reply = g_variant_new_string (result);
	_g_free0 (result);
	return _reply;
}

static GVariant*
bluez_dbus_interface_get_property (GDBusConnection* connection,
                                   const gchar* sender,
                                   const gchar* object_path,
                                   const gchar* interface_name,
                                   const gchar* property_name,
                                   GError** error,
                                   gpointer user_data)
{
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (property_name, "Address") == 0) {
		return _dbus_bluez_get_address (object);
	}
	return NULL;
}

static gboolean
bluez_dbus_interface_set_property (GDBusConnection* connection,
                                   const gchar* sender,
                                   const gchar* object_path,
                                   const gchar* interface_name,
                                   const gchar* property_name,
                                   GVariant* value,
                                   GError** error,
                                   gpointer user_data)
{
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}

static void
_dbus_bluez_discovery_started (GObject* _sender,
                               gpointer* _data)
{
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.bluez.Adapter1", "DiscoveryStarted", _arguments, NULL);
}

static void
_dbus_bluez_discovery_completed (GObject* _sender,
                                 gpointer* _data)
{
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.bluez.Adapter1", "DiscoveryCompleted", _arguments, NULL);
}

static void
_dbus_bluez_remote_device_found (GObject* _sender,
                                 const gchar* address,
                                 guint klass,
                                 gint rssi,
                                 gpointer* _data)
{
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (address));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_uint32 (klass));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_int32 (rssi));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.bluez.Adapter1", "RemoteDeviceFound", _arguments, NULL);
}

static void
_dbus_bluez_remote_name_updated (GObject* _sender,
                                 const gchar* address,
                                 const gchar* name,
                                 gpointer* _data)
{
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (address));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (name));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.bluez.Adapter1", "RemoteNameUpdated", _arguments, NULL);
}

guint
bluez_register_object (gpointer object,
                       GDBusConnection* connection,
                       const gchar* path,
                       GError** error)
{
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_bluez_dbus_interface_info), &_bluez_dbus_interface_vtable, data, _bluez_unregister_object, error);
	if (!result) {
		return 0;
	}
	g_signal_connect (object, "discovery-started", (GCallback) _dbus_bluez_discovery_started, data);
	g_signal_connect (object, "discovery-completed", (GCallback) _dbus_bluez_discovery_completed, data);
	g_signal_connect (object, "remote-device-found", (GCallback) _dbus_bluez_remote_device_found, data);
	g_signal_connect (object, "remote-name-updated", (GCallback) _dbus_bluez_remote_name_updated, data);
	return result;
}

static void
_bluez_unregister_object (gpointer user_data)
{
	gpointer* data;
	data = user_data;
	g_signal_handlers_disconnect_by_func (data[0], _dbus_bluez_discovery_started, data);
	g_signal_handlers_disconnect_by_func (data[0], _dbus_bluez_discovery_completed, data);
	g_signal_handlers_disconnect_by_func (data[0], _dbus_bluez_remote_device_found, data);
	g_signal_handlers_disconnect_by_func (data[0], _dbus_bluez_remote_name_updated, data);
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}

static inline gpointer
bluetooth_get_instance_private (Bluetooth* self)
{
	return G_STRUCT_MEMBER_P (self, Bluetooth_private_offset);
}

static void
bluetooth_on_remote_device_found (Bluetooth* self,
                                  const gchar* address,
                                  guint klass,
                                  gint rssi)
{
	FILE* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (address != NULL);
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Remote device found (%s, %u, %d)\n", address, klass, rssi);
}

static void
bluetooth_on_discovery_started (Bluetooth* self)
{
	FILE* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Discovery started\n");
}

static void
bluetooth_on_remote_name_updated (Bluetooth* self,
                                  const gchar* address,
                                  const gchar* name)
{
	FILE* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (address != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Remote name updated (%s, %s)\n", address, name);
}

static void
bluetooth_on_discovery_completed (Bluetooth* self)
{
	FILE* _tmp0_;
	GMainLoop* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Discovery completed\n");
	_tmp1_ = self->priv->loop;
	g_main_loop_quit (_tmp1_);
}

static void
_bluetooth_on_remote_device_found_bluez_remote_device_found (Bluez* _sender,
                                                             const gchar* address,
                                                             guint klass,
                                                             gint rssi,
                                                             gpointer self)
{
	bluetooth_on_remote_device_found ((Bluetooth*) self, address, klass, rssi);
}

static void
_bluetooth_on_discovery_started_bluez_discovery_started (Bluez* _sender,
                                                         gpointer self)
{
	bluetooth_on_discovery_started ((Bluetooth*) self);
}

static void
_bluetooth_on_discovery_completed_bluez_discovery_completed (Bluez* _sender,
                                                             gpointer self)
{
	bluetooth_on_discovery_completed ((Bluetooth*) self);
}

static void
_bluetooth_on_remote_name_updated_bluez_remote_name_updated (Bluez* _sender,
                                                             const gchar* address,
                                                             const gchar* name,
                                                             gpointer self)
{
	bluetooth_on_remote_name_updated ((Bluetooth*) self, address, name);
}

Bluetooth*
bluetooth_construct (GType object_type)
{
	Bluetooth * self = NULL;
	Bluez* bluez = NULL;
	GMainLoop* _tmp15_;
	GMainLoop* _tmp16_;
	GError* _inner_error0_ = NULL;
	self = (Bluetooth*) g_object_new (object_type, NULL);
	{
		Bluez* _tmp0_ = NULL;
		Bluez* _tmp1_;
		Bluez* _tmp2_;
		Bluez* _tmp3_;
		Bluez* _tmp4_;
		Bluez* _tmp5_;
		Bluez* _tmp6_;
		Bluez* _tmp7_;
		Bluez* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		_tmp1_ = (Bluez*) g_initable_new (TYPE_BLUEZ_PROXY, NULL, &_inner_error0_, "g-flags", 0, "g-name", "org.bluez", "g-bus-type", G_BUS_TYPE_SYSTEM, "g-object-path", "/org/bluez/hci0", "g-interface-name", "org.bluez.Adapter1", NULL);
		_tmp0_ = (Bluez*) _tmp1_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp2_ = _tmp0_;
		_tmp0_ = NULL;
		_g_object_unref0 (bluez);
		bluez = _tmp2_;
		_tmp3_ = bluez;
		g_signal_connect_object (_tmp3_, "remote-device-found", (GCallback) _bluetooth_on_remote_device_found_bluez_remote_device_found, self, 0);
		_tmp4_ = bluez;
		g_signal_connect_object (_tmp4_, "discovery-started", (GCallback) _bluetooth_on_discovery_started_bluez_discovery_started, self, 0);
		_tmp5_ = bluez;
		g_signal_connect_object (_tmp5_, "discovery-completed", (GCallback) _bluetooth_on_discovery_completed_bluez_discovery_completed, self, 0);
		_tmp6_ = bluez;
		g_signal_connect_object (_tmp6_, "remote-name-updated", (GCallback) _bluetooth_on_remote_name_updated_bluez_remote_name_updated, self, 0);
		_tmp7_ = bluez;
		bluez_start_discovery (_tmp7_, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (_tmp0_);
			goto __catch0_g_error;
		}
		_tmp8_ = bluez;
		_tmp9_ = bluez_get_address (_tmp8_);
		_tmp10_ = _tmp9_;
		_tmp11_ = _tmp10_;
		g_print ("%s", _tmp11_);
		_g_free0 (_tmp11_);
		_g_object_unref0 (_tmp0_);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp12_;
		GError* _tmp13_;
		const gchar* _tmp14_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp12_ = stderr;
		_tmp13_ = e;
		_tmp14_ = _tmp13_->message;
		fprintf (_tmp12_, "%s\n", _tmp14_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (bluez);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
	_tmp15_ = g_main_loop_new (NULL, FALSE);
	_g_main_loop_unref0 (self->priv->loop);
	self->priv->loop = _tmp15_;
	_tmp16_ = self->priv->loop;
	g_main_loop_run (_tmp16_);
	_g_object_unref0 (bluez);
	return self;
}

Bluetooth*
bluetooth_new (void)
{
	return bluetooth_construct (TYPE_BLUETOOTH);
}

static void
bluetooth_class_init (BluetoothClass * klass,
                      gpointer klass_data)
{
	bluetooth_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &Bluetooth_private_offset);
	G_OBJECT_CLASS (klass)->finalize = bluetooth_finalize;
}

static void
bluetooth_instance_init (Bluetooth * self,
                         gpointer klass)
{
	self->priv = bluetooth_get_instance_private (self);
}

static void
bluetooth_finalize (GObject * obj)
{
	Bluetooth * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_BLUETOOTH, Bluetooth);
	_g_main_loop_unref0 (self->priv->loop);
	G_OBJECT_CLASS (bluetooth_parent_class)->finalize (obj);
}

static GType
bluetooth_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BluetoothClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bluetooth_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Bluetooth), 0, (GInstanceInitFunc) bluetooth_instance_init, NULL };
	GType bluetooth_type_id;
	bluetooth_type_id = g_type_register_static (G_TYPE_OBJECT, "Bluetooth", &g_define_type_info, 0);
	Bluetooth_private_offset = g_type_add_instance_private (bluetooth_type_id, sizeof (BluetoothPrivate));
	return bluetooth_type_id;
}

GType
bluetooth_get_type (void)
{
	static volatile gsize bluetooth_type_id__once = 0;
	if (g_once_init_enter (&bluetooth_type_id__once)) {
		GType bluetooth_type_id;
		bluetooth_type_id = bluetooth_get_type_once ();
		g_once_init_leave (&bluetooth_type_id__once, bluetooth_type_id);
	}
	return bluetooth_type_id__once;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

