/* Brightness.c generated by valac 0.56.16, the Vala compiler
 * generated from Brightness.vala, do not modify */

#include "Brightness.h"
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include "Hyprland.h"
#include <glib-object.h>
#include "Utils.h"

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

enum  {
	BRIGHTNESS_0_PROPERTY,
	BRIGHTNESS_LEVEL_PROPERTY,
	BRIGHTNESS_ICON_NAME_PROPERTY,
	BRIGHTNESS_NUM_PROPERTIES
};
static GParamSpec* brightness_properties[BRIGHTNESS_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
enum  {
	BRIGHTNESS_SIG_BRIGHTNESS_CHANGE_SIGNAL,
	BRIGHTNESS_NUM_SIGNALS
};
static guint brightness_signals[BRIGHTNESS_NUM_SIGNALS] = {0};

struct _BrightnessPrivate {
	gint _level;
	gchar* _icon_name;
	Hyprland* hypr;
};

static gint Brightness_private_offset;
static gpointer brightness_parent_class = NULL;

static void brightness_get_brightness_level (Brightness* self);
static void brightness_set_icon_name (Brightness* self,
                               const gchar* value);
static void brightness_restore_state (Brightness* self);
static void brightness_set_level (Brightness* self,
                           gint value);
static void brightness_save_state (Brightness* self);
static void brightness_finalize (GObject * obj);
static GType brightness_get_type_once (void);
static void _vala_brightness_get_property (GObject * object,
                                    guint property_id,
                                    GValue * value,
                                    GParamSpec * pspec);
static void _vala_brightness_set_property (GObject * object,
                                    guint property_id,
                                    const GValue * value,
                                    GParamSpec * pspec);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);

static inline gpointer
brightness_get_instance_private (Brightness* self)
{
	return G_STRUCT_MEMBER_P (self, Brightness_private_offset);
}

Brightness*
brightness_construct (GType object_type)
{
	Brightness * self = NULL;
	Hyprland* _tmp0_;
	self = (Brightness*) g_object_new (object_type, NULL);
	_tmp0_ = hyprland_new ();
	_g_object_unref0 (self->priv->hypr);
	self->priv->hypr = _tmp0_;
	return self;
}

Brightness*
brightness_new (void)
{
	return brightness_construct (TYPE_BRIGHTNESS);
}

void
brightness_start (Brightness* self)
{
	g_return_if_fail (self != NULL);
	brightness_get_brightness_level (self);
	brightness_set_icon_name (self, "display-brightness-symbolic");
	brightness_restore_state (self);
}

void
brightness_set_brightness (Brightness* self,
                           gint level)
{
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	if (0 <= level) {
		_tmp0_ = level <= 100;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		Hyprland* _tmp1_;
		gchar* _tmp2_;
		gchar* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
		gchar* _tmp7_;
		gint _tmp8_;
		_tmp1_ = self->priv->hypr;
		_tmp2_ = g_strdup_printf ("%i", level);
		_tmp3_ = _tmp2_;
		_tmp4_ = g_strconcat ("brightnessctl set ", _tmp3_, "%", NULL);
		_tmp5_ = _tmp4_;
		_tmp6_ = hyprland_dispatch_exec (_tmp1_, _tmp5_);
		_tmp7_ = _tmp6_;
		_g_free0 (_tmp7_);
		_g_free0 (_tmp5_);
		_g_free0 (_tmp3_);
		brightness_set_level (self, level);
		brightness_save_state (self);
		_tmp8_ = self->priv->_level;
		g_signal_emit (self, brightness_signals[BRIGHTNESS_SIG_BRIGHTNESS_CHANGE_SIGNAL], 0, _tmp8_);
	}
}

static void
brightness_save_state (Brightness* self)
{
	Hyprland* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->hypr;
	_tmp1_ = hyprland_dispatch_exec (_tmp0_, "brightnessct --save");
	_tmp2_ = _tmp1_;
	_g_free0 (_tmp2_);
}

static void
brightness_restore_state (Brightness* self)
{
	Hyprland* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->hypr;
	_tmp1_ = hyprland_dispatch_exec (_tmp0_, "brightnessctl --restore");
	_tmp2_ = _tmp1_;
	_g_free0 (_tmp2_);
}

static void
brightness_get_brightness_level (Brightness* self)
{
	gchar* res = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar** _tmp2_;
	gchar** _tmp3_;
	gint _tmp3__length1;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar** _tmp6_;
	gchar** _tmp7_;
	gchar** _tmp8_;
	gint _tmp8__length1;
	const gchar* _tmp9_;
	gint _tmp10_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("brightnessctl");
	_tmp1_ = g_strdup ("-m");
	_tmp2_ = g_new0 (gchar*, 2 + 1);
	_tmp2_[0] = _tmp0_;
	_tmp2_[1] = _tmp1_;
	_tmp3_ = _tmp2_;
	_tmp3__length1 = 2;
	_tmp4_ = utils_exec (_tmp3_, (gint) 2);
	_tmp5_ = _tmp4_;
	_tmp3_ = (_vala_array_free (_tmp3_, _tmp3__length1, (GDestroyNotify) g_free), NULL);
	res = _tmp5_;
	_tmp7_ = _tmp6_ = g_strsplit (res, ",", 0);
	_tmp8_ = _tmp7_;
	_tmp8__length1 = _vala_array_length (_tmp6_);
	_tmp9_ = _tmp8_[3];
	brightness_set_level (self, atoi (_tmp9_));
	_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) g_free), NULL);
	_tmp10_ = self->priv->_level;
	g_signal_emit (self, brightness_signals[BRIGHTNESS_SIG_BRIGHTNESS_CHANGE_SIGNAL], 0, _tmp10_);
	_g_free0 (res);
}

gint
brightness_get_level (Brightness* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_level;
	return result;
}

static void
brightness_set_level (Brightness* self,
                      gint value)
{
	gint old_value;
	g_return_if_fail (self != NULL);
	old_value = brightness_get_level (self);
	if (old_value != value) {
		self->priv->_level = value;
		g_object_notify_by_pspec ((GObject *) self, brightness_properties[BRIGHTNESS_LEVEL_PROPERTY]);
	}
}

const gchar*
brightness_get_icon_name (Brightness* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_icon_name;
	result = _tmp0_;
	return result;
}

static void
brightness_set_icon_name (Brightness* self,
                          const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = brightness_get_icon_name (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_icon_name);
		self->priv->_icon_name = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, brightness_properties[BRIGHTNESS_ICON_NAME_PROPERTY]);
	}
}

static void
brightness_class_init (BrightnessClass * klass,
                       gpointer klass_data)
{
	brightness_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &Brightness_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_brightness_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_brightness_set_property;
	G_OBJECT_CLASS (klass)->finalize = brightness_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), BRIGHTNESS_LEVEL_PROPERTY, brightness_properties[BRIGHTNESS_LEVEL_PROPERTY] = g_param_spec_int ("level", "level", "level", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), BRIGHTNESS_ICON_NAME_PROPERTY, brightness_properties[BRIGHTNESS_ICON_NAME_PROPERTY] = g_param_spec_string ("icon-name", "icon-name", "icon-name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	brightness_signals[BRIGHTNESS_SIG_BRIGHTNESS_CHANGE_SIGNAL] = g_signal_new ("sig-brightness-change", TYPE_BRIGHTNESS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__INT, G_TYPE_NONE, 1, G_TYPE_INT);
}

static void
brightness_instance_init (Brightness * self,
                          gpointer klass)
{
	gchar* _tmp0_;
	self->priv = brightness_get_instance_private (self);
	self->priv->_level = 0;
	_tmp0_ = g_strdup ("display-brightness-symbolic");
	self->priv->_icon_name = _tmp0_;
}

static void
brightness_finalize (GObject * obj)
{
	Brightness * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_BRIGHTNESS, Brightness);
	_g_free0 (self->priv->_icon_name);
	_g_object_unref0 (self->priv->hypr);
	G_OBJECT_CLASS (brightness_parent_class)->finalize (obj);
}

static GType
brightness_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BrightnessClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) brightness_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Brightness), 0, (GInstanceInitFunc) brightness_instance_init, NULL };
	GType brightness_type_id;
	brightness_type_id = g_type_register_static (G_TYPE_OBJECT, "Brightness", &g_define_type_info, 0);
	Brightness_private_offset = g_type_add_instance_private (brightness_type_id, sizeof (BrightnessPrivate));
	return brightness_type_id;
}

GType
brightness_get_type (void)
{
	static volatile gsize brightness_type_id__once = 0;
	if (g_once_init_enter (&brightness_type_id__once)) {
		GType brightness_type_id;
		brightness_type_id = brightness_get_type_once ();
		g_once_init_leave (&brightness_type_id__once, brightness_type_id);
	}
	return brightness_type_id__once;
}

static void
_vala_brightness_get_property (GObject * object,
                               guint property_id,
                               GValue * value,
                               GParamSpec * pspec)
{
	Brightness * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_BRIGHTNESS, Brightness);
	switch (property_id) {
		case BRIGHTNESS_LEVEL_PROPERTY:
		g_value_set_int (value, brightness_get_level (self));
		break;
		case BRIGHTNESS_ICON_NAME_PROPERTY:
		g_value_set_string (value, brightness_get_icon_name (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_brightness_set_property (GObject * object,
                               guint property_id,
                               const GValue * value,
                               GParamSpec * pspec)
{
	Brightness * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_BRIGHTNESS, Brightness);
	switch (property_id) {
		case BRIGHTNESS_LEVEL_PROPERTY:
		brightness_set_level (self, g_value_get_int (value));
		break;
		case BRIGHTNESS_ICON_NAME_PROPERTY:
		brightness_set_icon_name (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

