/* Hyprland.c generated by valac 0.56.16, the Vala compiler
 * generated from Hyprland.vala, do not modify */

#include "Hyprland.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include "Utils.h"
#include <json-glib/json-glib.h>
#include <gio/gio.h>
#include <stdio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _g_free0(var) (var = (g_free (var), NULL))
enum  {
	HYPRLAND_0_PROPERTY,
	HYPRLAND_ACTIVEWINDOW_PROPERTY,
	HYPRLAND_NUM_PROPERTIES
};
static GParamSpec* hyprland_properties[HYPRLAND_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))
enum  {
	HYPRLAND_SIG_CHANGE_SIGNAL,
	HYPRLAND_SIG_ACTIVEWINDOW_SIGNAL,
	HYPRLAND_SIG_WORKSPACES_SIGNAL,
	HYPRLAND_SIG_CLIENTS_SIGNAL,
	HYPRLAND_SIG_CURRENT_WORKSPACE_CLIENTS_SIGNAL,
	HYPRLAND_NUM_SIGNALS
};
static guint hyprland_signals[HYPRLAND_NUM_SIGNALS] = {0};

struct _HyprlandPrivate {
	HyprWindow _activewindow;
};

static gint Hyprland_private_offset;
static gpointer hyprland_parent_class = NULL;

static gint64* _vala_array_dup1 (gint64* self,
                          gssize length);
static gint64* _vala_array_dup2 (gint64* self,
                          gssize length);
static void _vala_HyprWorkspace_array_free (HyprWorkspace * array,
                                     gssize array_length);
static void _vala_HyprWindow_array_free (HyprWindow * array,
                                  gssize array_length);
static void hyprland_set_active_window (Hyprland* self);
static void hyprland_set_workspaces (Hyprland* self);
static void hyprland_set_clients (Hyprland* self);
static void hyprland_set_current_workspace_clients (Hyprland* self);
static void hyprland_hypr (Hyprland* self);
static void hyprland_send_signals (Hyprland* self);
static void __lambda4_ (Hyprland* self,
                 const gchar* action);
static void hyprland_do_action (Hyprland* self,
                         const gchar* action);
static void ___lambda4__utils_exec_threads_output (UtilsExec_Threads* _sender,
                                            const gchar* o,
                                            gpointer self);
static void hyprland_set_actual_workspaces_len (Hyprland* self);
static gchar* hyprland_read (Hyprland* self,
                      gchar** command,
                      gint command_length1);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
static void hyprland_get_client (Hyprland* self,
                          JsonObject* obj,
                          HyprWindow* result);
static void hyprland_set_activewindow (Hyprland* self,
                                HyprWindow * value);
static void _vala_JsonNode_free (JsonNode* self);
static gchar* hyprland_read_all (Hyprland* self,
                          GInputStream* inp);
static gboolean _hypr_workspace_equal (const HyprWorkspace * s1,
                                const HyprWorkspace * s2);
static gboolean _hypr_window_equal (const HyprWindow * s1,
                             const HyprWindow * s2);
static void g_cclosure_user_marshal_VOID__POINTER_INT (GClosure * closure,
                                                GValue * return_value,
                                                guint n_param_values,
                                                const GValue * param_values,
                                                gpointer invocation_hint,
                                                gpointer marshal_data);
static void hyprland_finalize (GObject * obj);
static GType hyprland_get_type_once (void);
static void _vala_hyprland_get_property (GObject * object,
                                  guint property_id,
                                  GValue * value,
                                  GParamSpec * pspec);
static void _vala_hyprland_set_property (GObject * object,
                                  guint property_id,
                                  const GValue * value,
                                  GParamSpec * pspec);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

void
hypr_workspace_copy (const HyprWorkspace* self,
                     HyprWorkspace* dest)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	(*dest).id = (*self).id;
	_tmp0_ = (*self).name;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).name);
	(*dest).name = _tmp1_;
	_tmp2_ = (*self).monitor;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 ((*dest).monitor);
	(*dest).monitor = _tmp3_;
	(*dest).monitorID = (*self).monitorID;
	(*dest).windows = (*self).windows;
	(*dest).hasfullscreen = (*self).hasfullscreen;
	_tmp4_ = (*self).lastwindow;
	_tmp5_ = g_strdup (_tmp4_);
	_g_free0 ((*dest).lastwindow);
	(*dest).lastwindow = _tmp5_;
	_tmp6_ = (*self).lastwindowtitle;
	_tmp7_ = g_strdup (_tmp6_);
	_g_free0 ((*dest).lastwindowtitle);
	(*dest).lastwindowtitle = _tmp7_;
}

void
hypr_workspace_destroy (HyprWorkspace* self)
{
	_g_free0 ((*self).name);
	_g_free0 ((*self).monitor);
	_g_free0 ((*self).lastwindow);
	_g_free0 ((*self).lastwindowtitle);
}

HyprWorkspace*
hypr_workspace_dup (const HyprWorkspace* self)
{
	HyprWorkspace* dup;
	dup = g_new0 (HyprWorkspace, 1);
	hypr_workspace_copy (self, dup);
	return dup;
}

void
hypr_workspace_free (HyprWorkspace* self)
{
	hypr_workspace_destroy (self);
	g_free (self);
}

static GType
hypr_workspace_get_type_once (void)
{
	GType hypr_workspace_type_id;
	hypr_workspace_type_id = g_boxed_type_register_static ("HyprWorkspace", (GBoxedCopyFunc) hypr_workspace_dup, (GBoxedFreeFunc) hypr_workspace_free);
	return hypr_workspace_type_id;
}

GType
hypr_workspace_get_type (void)
{
	static volatile gsize hypr_workspace_type_id__once = 0;
	if (g_once_init_enter (&hypr_workspace_type_id__once)) {
		GType hypr_workspace_type_id;
		hypr_workspace_type_id = hypr_workspace_get_type_once ();
		g_once_init_leave (&hypr_workspace_type_id__once, hypr_workspace_type_id);
	}
	return hypr_workspace_type_id__once;
}

static gint64*
_vala_array_dup1 (gint64* self,
                  gssize length)
{
	if (length > 0) {
		return _vala_memdup2 (self, length * sizeof (gint64));
	}
	return NULL;
}

static gint64*
_vala_array_dup2 (gint64* self,
                  gssize length)
{
	if (length > 0) {
		return _vala_memdup2 (self, length * sizeof (gint64));
	}
	return NULL;
}

void
hypr_window_copy (const HyprWindow* self,
                  HyprWindow* dest)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	HyprWorkspace _tmp2_;
	HyprWorkspace _tmp3_;
	HyprWorkspace _tmp4_ = {0};
	const gchar* _tmp5_;
	gchar* _tmp6_;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	const gchar* _tmp9_;
	gchar* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	gint64* _tmp13_;
	gint _tmp13__length1;
	gint64* _tmp14_;
	gint _tmp14__length1;
	gint64* _tmp15_;
	gint _tmp15__length1;
	gint64* _tmp16_;
	gint _tmp16__length1;
	const gchar* _tmp17_;
	gchar* _tmp18_;
	_tmp0_ = (*self).address;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).address);
	(*dest).address = _tmp1_;
	(*dest).mapped = (*self).mapped;
	(*dest).hidden = (*self).hidden;
	memcpy ((*dest).at, (*self).at, 2 * sizeof (gint64));
	memcpy ((*dest).size, (*self).size, 2 * sizeof (gint64));
	_tmp2_ = (*self).workspace;
	_tmp3_ = _tmp2_;
	hypr_workspace_copy (&_tmp3_, &_tmp4_);
	hypr_workspace_destroy (&(*dest).workspace);
	(*dest).workspace = _tmp4_;
	(*dest).floating = (*self).floating;
	(*dest).pseudo = (*self).pseudo;
	(*dest).monitor = (*self).monitor;
	_tmp5_ = (*self).class;
	_tmp6_ = g_strdup (_tmp5_);
	_g_free0 ((*dest).class);
	(*dest).class = _tmp6_;
	_tmp7_ = (*self).title;
	_tmp8_ = g_strdup (_tmp7_);
	_g_free0 ((*dest).title);
	(*dest).title = _tmp8_;
	_tmp9_ = (*self).initialClass;
	_tmp10_ = g_strdup (_tmp9_);
	_g_free0 ((*dest).initialClass);
	(*dest).initialClass = _tmp10_;
	_tmp11_ = (*self).initialTitle;
	_tmp12_ = g_strdup (_tmp11_);
	_g_free0 ((*dest).initialTitle);
	(*dest).initialTitle = _tmp12_;
	(*dest).pid = (*self).pid;
	(*dest).xwayland = (*self).xwayland;
	(*dest).pinned = (*self).pinned;
	(*dest).fullscreen = (*self).fullscreen;
	(*dest).fullscreenClient = (*self).fullscreenClient;
	_tmp13_ = (*self).grouped;
	_tmp13__length1 = (*self).grouped_length1;
	_tmp14_ = (_tmp13_ != NULL) ? _vala_array_dup1 (_tmp13_, _tmp13__length1) : _tmp13_;
	_tmp14__length1 = _tmp13__length1;
	(*dest).grouped = (g_free ((*dest).grouped), NULL);
	(*dest).grouped = _tmp14_;
	(*dest).grouped_length1 = _tmp14__length1;
	_tmp15_ = (*self).tags;
	_tmp15__length1 = (*self).tags_length1;
	_tmp16_ = (_tmp15_ != NULL) ? _vala_array_dup2 (_tmp15_, _tmp15__length1) : _tmp15_;
	_tmp16__length1 = _tmp15__length1;
	(*dest).tags = (g_free ((*dest).tags), NULL);
	(*dest).tags = _tmp16_;
	(*dest).tags_length1 = _tmp16__length1;
	_tmp17_ = (*self).swallowing;
	_tmp18_ = g_strdup (_tmp17_);
	_g_free0 ((*dest).swallowing);
	(*dest).swallowing = _tmp18_;
	(*dest).focusHistoryID = (*self).focusHistoryID;
}

void
hypr_window_destroy (HyprWindow* self)
{
	_g_free0 ((*self).address);
	hypr_workspace_destroy (&(*self).workspace);
	_g_free0 ((*self).class);
	_g_free0 ((*self).title);
	_g_free0 ((*self).initialClass);
	_g_free0 ((*self).initialTitle);
	(*self).grouped = (g_free ((*self).grouped), NULL);
	(*self).tags = (g_free ((*self).tags), NULL);
	_g_free0 ((*self).swallowing);
}

HyprWindow*
hypr_window_dup (const HyprWindow* self)
{
	HyprWindow* dup;
	dup = g_new0 (HyprWindow, 1);
	hypr_window_copy (self, dup);
	return dup;
}

void
hypr_window_free (HyprWindow* self)
{
	hypr_window_destroy (self);
	g_free (self);
}

static GType
hypr_window_get_type_once (void)
{
	GType hypr_window_type_id;
	hypr_window_type_id = g_boxed_type_register_static ("HyprWindow", (GBoxedCopyFunc) hypr_window_dup, (GBoxedFreeFunc) hypr_window_free);
	return hypr_window_type_id;
}

GType
hypr_window_get_type (void)
{
	static volatile gsize hypr_window_type_id__once = 0;
	if (g_once_init_enter (&hypr_window_type_id__once)) {
		GType hypr_window_type_id;
		hypr_window_type_id = hypr_window_get_type_once ();
		g_once_init_leave (&hypr_window_type_id__once, hypr_window_type_id);
	}
	return hypr_window_type_id__once;
}

static inline gpointer
hyprland_get_instance_private (Hyprland* self)
{
	return G_STRUCT_MEMBER_P (self, Hyprland_private_offset);
}

static void
_vala_HyprWorkspace_array_free (HyprWorkspace * array,
                                gssize array_length)
{
	if (array != NULL) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			hypr_workspace_destroy (&array[i]);
		}
	}
	g_free (array);
}

static void
_vala_HyprWindow_array_free (HyprWindow * array,
                             gssize array_length)
{
	if (array != NULL) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			hypr_window_destroy (&array[i]);
		}
	}
	g_free (array);
}

Hyprland*
hyprland_construct (GType object_type)
{
	Hyprland * self = NULL;
	self = (Hyprland*) g_object_new (object_type, NULL);
	hyprland_set_active_window (self);
	hyprland_set_workspaces (self);
	hyprland_set_clients (self);
	hyprland_set_current_workspace_clients (self);
	return self;
}

Hyprland*
hyprland_new (void)
{
	return hyprland_construct (TYPE_HYPRLAND);
}

void
hyprland_start (Hyprland* self)
{
	g_return_if_fail (self != NULL);
	hyprland_hypr (self);
	hyprland_send_signals (self);
}

static void
hyprland_send_signals (Hyprland* self)
{
	HyprWindow _tmp0_;
	HyprWorkspace* _tmp1_;
	gint _tmp1__length1;
	HyprWindow* _tmp2_;
	gint _tmp2__length1;
	HyprWindow* _tmp3_;
	gint _tmp3__length1;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_activewindow;
	g_signal_emit (self, hyprland_signals[HYPRLAND_SIG_ACTIVEWINDOW_SIGNAL], 0, &_tmp0_);
	_tmp1_ = self->workspaces;
	_tmp1__length1 = self->workspaces_length1;
	g_signal_emit (self, hyprland_signals[HYPRLAND_SIG_WORKSPACES_SIGNAL], 0, _tmp1_, (gint) _tmp1__length1);
	_tmp2_ = self->clients;
	_tmp2__length1 = self->clients_length1;
	g_signal_emit (self, hyprland_signals[HYPRLAND_SIG_CLIENTS_SIGNAL], 0, _tmp2_, (gint) _tmp2__length1);
	_tmp3_ = self->current_workspace_clients;
	_tmp3__length1 = self->current_workspace_clients_length1;
	g_signal_emit (self, hyprland_signals[HYPRLAND_SIG_CURRENT_WORKSPACE_CLIENTS_SIGNAL], 0, _tmp3_, (gint) _tmp3__length1);
	g_signal_emit (self, hyprland_signals[HYPRLAND_SIG_CHANGE_SIGNAL], 0);
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static void
__lambda4_ (Hyprland* self,
            const gchar* action)
{
	g_return_if_fail (action != NULL);
	hyprland_do_action (self, action);
}

static void
___lambda4__utils_exec_threads_output (UtilsExec_Threads* _sender,
                                       const gchar* o,
                                       gpointer self)
{
	__lambda4_ ((Hyprland*) self, o);
}

static void
hyprland_hypr (Hyprland* self)
{
	gchar* HYPRLAND_INSTANCE_SIGNATURE = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar** command = NULL;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	gchar** _tmp7_;
	gint command_length1;
	gint _command_size_;
	UtilsExec_Threads* thread = NULL;
	UtilsExec_Threads* _tmp8_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_getenv ("HYPRLAND_INSTANCE_SIGNATURE");
	_tmp1_ = g_strdup (_tmp0_);
	HYPRLAND_INSTANCE_SIGNATURE = _tmp1_;
	_tmp2_ = g_strdup ("socat");
	_tmp3_ = g_strdup ("-U");
	_tmp4_ = g_strdup ("-");
	_tmp5_ = string_to_string (HYPRLAND_INSTANCE_SIGNATURE);
	_tmp6_ = g_strconcat ("UNIX-CONNECT:/run/user/1000/hypr/", _tmp5_, "/.socket2.sock", NULL);
	_tmp7_ = g_new0 (gchar*, 4 + 1);
	_tmp7_[0] = _tmp2_;
	_tmp7_[1] = _tmp3_;
	_tmp7_[2] = _tmp4_;
	_tmp7_[3] = _tmp6_;
	command = _tmp7_;
	command_length1 = 4;
	_command_size_ = command_length1;
	_tmp8_ = utils_exec_threads_new (command, command_length1, "hypr");
	thread = _tmp8_;
	g_signal_connect_object (thread, "output", (GCallback) ___lambda4__utils_exec_threads_output, self, 0);
	utils_exec_threads_start (thread);
	_g_object_unref0 (thread);
	command = (_vala_array_free (command, command_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (HYPRLAND_INSTANCE_SIGNATURE);
}

static void
hyprland_do_action (Hyprland* self,
                    const gchar* action)
{
	gchar** action_break = NULL;
	gchar** _tmp0_;
	gchar** _tmp1_;
	gint action_break_length1;
	gint _action_break_size_;
	gchar* action_type = NULL;
	gchar** _tmp2_;
	gint _tmp2__length1;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* action_value = NULL;
	gchar** _tmp5_;
	gint _tmp5__length1;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	GQuark _tmp11_ = 0U;
	static GQuark _tmp10_label0 = 0;
	static GQuark _tmp10_label1 = 0;
	static GQuark _tmp10_label2 = 0;
	static GQuark _tmp10_label3 = 0;
	static GQuark _tmp10_label4 = 0;
	static GQuark _tmp10_label5 = 0;
	static GQuark _tmp10_label6 = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (action != NULL);
	_tmp1_ = _tmp0_ = g_strsplit (action, ">>", 0);
	action_break = _tmp1_;
	action_break_length1 = _vala_array_length (_tmp0_);
	_action_break_size_ = action_break_length1;
	_tmp2_ = action_break;
	_tmp2__length1 = action_break_length1;
	_tmp3_ = _tmp2_[0];
	_tmp4_ = g_strdup (_tmp3_);
	action_type = _tmp4_;
	_tmp5_ = action_break;
	_tmp5__length1 = action_break_length1;
	_tmp6_ = _tmp5_[1];
	_tmp7_ = g_strdup (_tmp6_);
	action_value = _tmp7_;
	_tmp8_ = action_type;
	_tmp9_ = _tmp8_;
	_tmp11_ = (NULL == _tmp9_) ? 0 : g_quark_from_string (_tmp9_);
	if (_tmp11_ == ((0 != _tmp10_label0) ? _tmp10_label0 : (_tmp10_label0 = g_quark_from_static_string ("activewindowv2")))) {
		switch (0) {
			default:
			{
				HyprWindow _tmp12_;
				hyprland_set_active_window (self);
				_tmp12_ = self->priv->_activewindow;
				g_signal_emit (self, hyprland_signals[HYPRLAND_SIG_ACTIVEWINDOW_SIGNAL], 0, &_tmp12_);
				break;
			}
		}
	} else if (_tmp11_ == ((0 != _tmp10_label1) ? _tmp10_label1 : (_tmp10_label1 = g_quark_from_static_string ("windowtitlev2")))) {
		switch (0) {
			default:
			{
				break;
			}
		}
	} else if (_tmp11_ == ((0 != _tmp10_label2) ? _tmp10_label2 : (_tmp10_label2 = g_quark_from_static_string ("workspacev2")))) {
		switch (0) {
			default:
			{
				const gchar* _tmp13_;
				gchar** _tmp14_;
				gchar** _tmp15_;
				gchar** _tmp16_;
				gint _tmp16__length1;
				const gchar* _tmp17_;
				HyprWindow* _tmp18_;
				gint _tmp18__length1;
				HyprWorkspace* _tmp19_;
				gint _tmp19__length1;
				_tmp13_ = action_value;
				_tmp15_ = _tmp14_ = g_strsplit (_tmp13_, ",", 0);
				_tmp16_ = _tmp15_;
				_tmp16__length1 = _vala_array_length (_tmp14_);
				_tmp17_ = _tmp16_[0];
				self->current_workspace_id = atoi (_tmp17_);
				_tmp16_ = (_vala_array_free (_tmp16_, _tmp16__length1, (GDestroyNotify) g_free), NULL);
				hyprland_set_current_workspace_clients (self);
				_tmp18_ = self->current_workspace_clients;
				_tmp18__length1 = self->current_workspace_clients_length1;
				g_signal_emit (self, hyprland_signals[HYPRLAND_SIG_CURRENT_WORKSPACE_CLIENTS_SIGNAL], 0, _tmp18_, (gint) _tmp18__length1);
				hyprland_set_workspaces (self);
				hyprland_set_actual_workspaces_len (self);
				_tmp19_ = self->workspaces;
				_tmp19__length1 = self->workspaces_length1;
				g_signal_emit (self, hyprland_signals[HYPRLAND_SIG_WORKSPACES_SIGNAL], 0, _tmp19_, (gint) _tmp19__length1);
				break;
			}
		}
	} else if (_tmp11_ == ((0 != _tmp10_label3) ? _tmp10_label3 : (_tmp10_label3 = g_quark_from_static_string ("createworkspacev2")))) {
		switch (0) {
			default:
			{
				HyprWorkspace* _tmp20_;
				gint _tmp20__length1;
				hyprland_set_workspaces (self);
				hyprland_set_actual_workspaces_len (self);
				_tmp20_ = self->workspaces;
				_tmp20__length1 = self->workspaces_length1;
				g_signal_emit (self, hyprland_signals[HYPRLAND_SIG_WORKSPACES_SIGNAL], 0, _tmp20_, (gint) _tmp20__length1);
				break;
			}
		}
	} else if (_tmp11_ == ((0 != _tmp10_label4) ? _tmp10_label4 : (_tmp10_label4 = g_quark_from_static_string ("destroyworkspacev2")))) {
		switch (0) {
			default:
			{
				HyprWorkspace* _tmp21_;
				gint _tmp21__length1;
				hyprland_set_workspaces (self);
				hyprland_set_actual_workspaces_len (self);
				_tmp21_ = self->workspaces;
				_tmp21__length1 = self->workspaces_length1;
				g_signal_emit (self, hyprland_signals[HYPRLAND_SIG_WORKSPACES_SIGNAL], 0, _tmp21_, (gint) _tmp21__length1);
				break;
			}
		}
	} else if (_tmp11_ == ((0 != _tmp10_label5) ? _tmp10_label5 : (_tmp10_label5 = g_quark_from_static_string ("openwindow")))) {
		switch (0) {
			default:
			{
				HyprWindow* _tmp22_;
				gint _tmp22__length1;
				hyprland_set_clients (self);
				_tmp22_ = self->clients;
				_tmp22__length1 = self->clients_length1;
				g_signal_emit (self, hyprland_signals[HYPRLAND_SIG_CLIENTS_SIGNAL], 0, _tmp22_, (gint) _tmp22__length1);
				break;
			}
		}
	} else if (_tmp11_ == ((0 != _tmp10_label6) ? _tmp10_label6 : (_tmp10_label6 = g_quark_from_static_string ("closewindow")))) {
		switch (0) {
			default:
			{
				HyprWindow* _tmp23_;
				gint _tmp23__length1;
				hyprland_set_clients (self);
				_tmp23_ = self->clients;
				_tmp23__length1 = self->clients_length1;
				g_signal_emit (self, hyprland_signals[HYPRLAND_SIG_CLIENTS_SIGNAL], 0, _tmp23_, (gint) _tmp23__length1);
				break;
			}
		}
	}
	_g_free0 (action_value);
	_g_free0 (action_type);
	action_break = (_vala_array_free (action_break, action_break_length1, (GDestroyNotify) g_free), NULL);
}

static JsonNode*
_vala_JsonNode_copy (JsonNode* self)
{
	return g_boxed_copy (json_node_get_type (), self);
}

static gpointer
__vala_JsonNode_copy0 (gpointer self)
{
	return self ? _vala_JsonNode_copy (self) : NULL;
}

static gpointer
_json_object_ref0 (gpointer self)
{
	return self ? json_object_ref (self) : NULL;
}

static void
_vala_JsonNode_free (JsonNode* self)
{
	g_boxed_free (json_node_get_type (), self);
}

static void
hyprland_set_active_window (Hyprland* self)
{
	gchar** command = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar** _tmp3_;
	gint command_length1;
	gint _command_size_;
	gchar* data = NULL;
	gchar** _tmp4_;
	gint _tmp4__length1;
	gchar* _tmp5_;
	const gchar* _tmp6_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("hyprctl");
	_tmp1_ = g_strdup ("activewindow");
	_tmp2_ = g_strdup ("-j");
	_tmp3_ = g_new0 (gchar*, 3 + 1);
	_tmp3_[0] = _tmp0_;
	_tmp3_[1] = _tmp1_;
	_tmp3_[2] = _tmp2_;
	command = _tmp3_;
	command_length1 = 3;
	_command_size_ = command_length1;
	_tmp4_ = command;
	_tmp4__length1 = command_length1;
	_tmp5_ = hyprland_read (self, _tmp4_, (gint) _tmp4__length1);
	data = _tmp5_;
	_tmp6_ = data;
	if (g_strcmp0 (_tmp6_, "{}\n") != 0) {
		JsonParser* parser = NULL;
		JsonParser* _tmp7_;
		JsonParser* _tmp8_;
		const gchar* _tmp9_;
		JsonNode* root = NULL;
		JsonParser* _tmp10_;
		JsonNode* _tmp11_;
		JsonNode* _tmp12_;
		JsonObject* obj = NULL;
		JsonNode* _tmp13_;
		JsonObject* _tmp14_;
		JsonObject* _tmp15_;
		JsonObject* _tmp16_;
		HyprWindow _tmp17_ = {0};
		HyprWindow _tmp18_;
		_tmp7_ = json_parser_new ();
		parser = _tmp7_;
		_tmp8_ = parser;
		_tmp9_ = data;
		json_parser_load_from_data (_tmp8_, _tmp9_, (gssize) -1, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (parser);
			_g_free0 (data);
			command = (_vala_array_free (command, command_length1, (GDestroyNotify) g_free), NULL);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
		_tmp10_ = parser;
		_tmp11_ = json_parser_get_root (_tmp10_);
		_tmp12_ = __vala_JsonNode_copy0 (_tmp11_);
		root = _tmp12_;
		_tmp13_ = root;
		_tmp14_ = json_node_get_object (_tmp13_);
		_tmp15_ = _json_object_ref0 (_tmp14_);
		obj = _tmp15_;
		_tmp16_ = obj;
		hyprland_get_client (self, _tmp16_, &_tmp17_);
		_tmp18_ = _tmp17_;
		hyprland_set_activewindow (self, &_tmp18_);
		hypr_window_destroy (&_tmp18_);
		_json_object_unref0 (obj);
		__vala_JsonNode_free0 (root);
		_g_object_unref0 (parser);
	}
	_g_free0 (data);
	command = (_vala_array_free (command, command_length1, (GDestroyNotify) g_free), NULL);
}

static gpointer
_json_array_ref0 (gpointer self)
{
	return self ? json_array_ref (self) : NULL;
}

static void
hyprland_set_clients (Hyprland* self)
{
	gchar** command = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar** _tmp3_;
	gint command_length1;
	gint _command_size_;
	gchar* data = NULL;
	gchar* _tmp4_;
	JsonParser* parser = NULL;
	JsonParser* _tmp5_;
	JsonNode* root = NULL;
	JsonNode* _tmp6_;
	JsonNode* _tmp7_;
	JsonArray* arr = NULL;
	JsonNode* _tmp8_;
	JsonArray* _tmp9_;
	JsonArray* _tmp10_;
	JsonArray* _tmp11_;
	GList* _tmp12_;
	GList* _tmp13_;
	HyprWindow* _tmp14_;
	gint i = 0;
	JsonArray* _tmp15_;
	GList* _tmp16_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("hyprctl");
	_tmp1_ = g_strdup ("clients");
	_tmp2_ = g_strdup ("-j");
	_tmp3_ = g_new0 (gchar*, 3 + 1);
	_tmp3_[0] = _tmp0_;
	_tmp3_[1] = _tmp1_;
	_tmp3_[2] = _tmp2_;
	command = _tmp3_;
	command_length1 = 3;
	_command_size_ = command_length1;
	_tmp4_ = hyprland_read (self, command, (gint) command_length1);
	data = _tmp4_;
	_tmp5_ = json_parser_new ();
	parser = _tmp5_;
	json_parser_load_from_data (parser, data, (gssize) -1, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (parser);
		_g_free0 (data);
		command = (_vala_array_free (command, command_length1, (GDestroyNotify) g_free), NULL);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp6_ = json_parser_get_root (parser);
	_tmp7_ = __vala_JsonNode_copy0 (_tmp6_);
	root = _tmp7_;
	_tmp8_ = root;
	_tmp9_ = json_node_get_array (_tmp8_);
	_tmp10_ = _json_array_ref0 (_tmp9_);
	arr = _tmp10_;
	_tmp11_ = arr;
	_tmp12_ = json_array_get_elements (_tmp11_);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_new0 (HyprWindow, g_list_length (_tmp13_));
	self->clients = (_vala_HyprWindow_array_free (self->clients, self->clients_length1), NULL);
	self->clients = _tmp14_;
	self->clients_length1 = g_list_length (_tmp13_);
	(_tmp13_ == NULL) ? NULL : (_tmp13_ = (g_list_free (_tmp13_), NULL));
	i = 0;
	_tmp15_ = arr;
	_tmp16_ = json_array_get_elements (_tmp15_);
	{
		GList* node_collection = NULL;
		GList* node_it = NULL;
		node_collection = _tmp16_;
		for (node_it = node_collection; node_it != NULL; node_it = node_it->next) {
			JsonNode* node = NULL;
			node = (JsonNode*) node_it->data;
			{
				HyprWindow* _tmp17_;
				gint _tmp17__length1;
				gint _tmp18_;
				JsonNode* _tmp19_;
				JsonObject* _tmp20_;
				HyprWindow _tmp21_ = {0};
				_tmp17_ = self->clients;
				_tmp17__length1 = self->clients_length1;
				_tmp18_ = i;
				i = _tmp18_ + 1;
				_tmp19_ = node;
				_tmp20_ = json_node_get_object (_tmp19_);
				hyprland_get_client (self, _tmp20_, &_tmp21_);
				hypr_window_destroy (&_tmp17_[_tmp18_]);
				_tmp17_[_tmp18_] = _tmp21_;
			}
		}
		(node_collection == NULL) ? NULL : (node_collection = (g_list_free (node_collection), NULL));
	}
	_json_array_unref0 (arr);
	__vala_JsonNode_free0 (root);
	_g_object_unref0 (parser);
	_g_free0 (data);
	command = (_vala_array_free (command, command_length1, (GDestroyNotify) g_free), NULL);
}

static void
hyprland_get_client (Hyprland* self,
                     JsonObject* obj,
                     HyprWindow* result)
{
	JsonNode* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	JsonNode* _tmp3_;
	JsonNode* _tmp4_;
	JsonNode* _tmp5_;
	JsonObject* _tmp6_;
	JsonNode* _tmp7_;
	JsonNode* _tmp8_;
	JsonObject* _tmp9_;
	JsonNode* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	HyprWorkspace _tmp13_ = {0};
	JsonNode* _tmp14_;
	JsonNode* _tmp15_;
	JsonNode* _tmp16_;
	JsonNode* _tmp17_;
	const gchar* _tmp18_;
	gchar* _tmp19_;
	JsonNode* _tmp20_;
	const gchar* _tmp21_;
	gchar* _tmp22_;
	JsonNode* _tmp23_;
	const gchar* _tmp24_;
	gchar* _tmp25_;
	JsonNode* _tmp26_;
	const gchar* _tmp27_;
	gchar* _tmp28_;
	JsonNode* _tmp29_;
	JsonNode* _tmp30_;
	JsonNode* _tmp31_;
	JsonNode* _tmp32_;
	JsonNode* _tmp33_;
	JsonNode* _tmp34_;
	const gchar* _tmp35_;
	gchar* _tmp36_;
	JsonNode* _tmp37_;
	HyprWindow _tmp38_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (obj != NULL);
	_tmp0_ = json_object_get_member (obj, "address");
	_tmp1_ = json_node_get_string (_tmp0_);
	_tmp2_ = g_strdup (_tmp1_);
	_tmp3_ = json_object_get_member (obj, "mapped");
	_tmp4_ = json_object_get_member (obj, "hidden");
	_tmp5_ = json_object_get_member (obj, "workspace");
	_tmp6_ = json_node_get_object (_tmp5_);
	_tmp7_ = json_object_get_member (_tmp6_, "id");
	_tmp8_ = json_object_get_member (obj, "workspace");
	_tmp9_ = json_node_get_object (_tmp8_);
	_tmp10_ = json_object_get_member (_tmp9_, "name");
	_tmp11_ = json_node_get_string (_tmp10_);
	_tmp12_ = g_strdup (_tmp11_);
	memset (&_tmp13_, 0, sizeof (HyprWorkspace));
	_tmp13_.id = json_node_get_int (_tmp7_);
	_g_free0 (_tmp13_.name);
	_tmp13_.name = _tmp12_;
	_tmp14_ = json_object_get_member (obj, "floating");
	_tmp15_ = json_object_get_member (obj, "pseudo");
	_tmp16_ = json_object_get_member (obj, "monitor");
	_tmp17_ = json_object_get_member (obj, "class");
	_tmp18_ = json_node_get_string (_tmp17_);
	_tmp19_ = g_strdup (_tmp18_);
	_tmp20_ = json_object_get_member (obj, "title");
	_tmp21_ = json_node_get_string (_tmp20_);
	_tmp22_ = g_strdup (_tmp21_);
	_tmp23_ = json_object_get_member (obj, "initialClass");
	_tmp24_ = json_node_get_string (_tmp23_);
	_tmp25_ = g_strdup (_tmp24_);
	_tmp26_ = json_object_get_member (obj, "initialTitle");
	_tmp27_ = json_node_get_string (_tmp26_);
	_tmp28_ = g_strdup (_tmp27_);
	_tmp29_ = json_object_get_member (obj, "pid");
	_tmp30_ = json_object_get_member (obj, "xwayland");
	_tmp31_ = json_object_get_member (obj, "pinned");
	_tmp32_ = json_object_get_member (obj, "fullscreen");
	_tmp33_ = json_object_get_member (obj, "fullscreenClient");
	_tmp34_ = json_object_get_member (obj, "swallowing");
	_tmp35_ = json_node_get_string (_tmp34_);
	_tmp36_ = g_strdup (_tmp35_);
	_tmp37_ = json_object_get_member (obj, "focusHistoryID");
	memset (&_tmp38_, 0, sizeof (HyprWindow));
	_g_free0 (_tmp38_.address);
	_tmp38_.address = _tmp2_;
	_tmp38_.mapped = json_node_get_boolean (_tmp3_);
	_tmp38_.hidden = json_node_get_boolean (_tmp4_);
	hypr_workspace_destroy (&_tmp38_.workspace);
	_tmp38_.workspace = _tmp13_;
	_tmp38_.floating = json_node_get_boolean (_tmp14_);
	_tmp38_.pseudo = json_node_get_boolean (_tmp15_);
	_tmp38_.monitor = json_node_get_int (_tmp16_);
	_g_free0 (_tmp38_.class);
	_tmp38_.class = _tmp19_;
	_g_free0 (_tmp38_.title);
	_tmp38_.title = _tmp22_;
	_g_free0 (_tmp38_.initialClass);
	_tmp38_.initialClass = _tmp25_;
	_g_free0 (_tmp38_.initialTitle);
	_tmp38_.initialTitle = _tmp28_;
	_tmp38_.pid = json_node_get_int (_tmp29_);
	_tmp38_.xwayland = json_node_get_boolean (_tmp30_);
	_tmp38_.pinned = json_node_get_boolean (_tmp31_);
	_tmp38_.fullscreen = json_node_get_int (_tmp32_);
	_tmp38_.fullscreenClient = json_node_get_int (_tmp33_);
	_g_free0 (_tmp38_.swallowing);
	_tmp38_.swallowing = _tmp36_;
	_tmp38_.focusHistoryID = json_node_get_int (_tmp37_);
	*result = _tmp38_;
	return;
}

static void
hyprland_set_workspaces (Hyprland* self)
{
	gchar** command = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar** _tmp3_;
	gint command_length1;
	gint _command_size_;
	gchar* data = NULL;
	gchar* _tmp4_;
	JsonParser* parser = NULL;
	JsonParser* _tmp5_;
	JsonNode* root = NULL;
	JsonNode* _tmp6_;
	JsonNode* _tmp7_;
	JsonArray* arr = NULL;
	JsonNode* _tmp8_;
	JsonArray* _tmp9_;
	JsonArray* _tmp10_;
	JsonArray* _tmp11_;
	GList* _tmp12_;
	GList* _tmp13_;
	HyprWorkspace* _tmp14_;
	gint i = 0;
	JsonArray* _tmp15_;
	GList* _tmp16_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("hyprctl");
	_tmp1_ = g_strdup ("workspaces");
	_tmp2_ = g_strdup ("-j");
	_tmp3_ = g_new0 (gchar*, 3 + 1);
	_tmp3_[0] = _tmp0_;
	_tmp3_[1] = _tmp1_;
	_tmp3_[2] = _tmp2_;
	command = _tmp3_;
	command_length1 = 3;
	_command_size_ = command_length1;
	_tmp4_ = hyprland_read (self, command, (gint) command_length1);
	data = _tmp4_;
	_tmp5_ = json_parser_new ();
	parser = _tmp5_;
	json_parser_load_from_data (parser, data, (gssize) -1, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (parser);
		_g_free0 (data);
		command = (_vala_array_free (command, command_length1, (GDestroyNotify) g_free), NULL);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_tmp6_ = json_parser_get_root (parser);
	_tmp7_ = __vala_JsonNode_copy0 (_tmp6_);
	root = _tmp7_;
	_tmp8_ = root;
	_tmp9_ = json_node_get_array (_tmp8_);
	_tmp10_ = _json_array_ref0 (_tmp9_);
	arr = _tmp10_;
	_tmp11_ = arr;
	_tmp12_ = json_array_get_elements (_tmp11_);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_new0 (HyprWorkspace, g_list_length (_tmp13_));
	self->workspaces = (_vala_HyprWorkspace_array_free (self->workspaces, self->workspaces_length1), NULL);
	self->workspaces = _tmp14_;
	self->workspaces_length1 = g_list_length (_tmp13_);
	(_tmp13_ == NULL) ? NULL : (_tmp13_ = (g_list_free (_tmp13_), NULL));
	i = 0;
	_tmp15_ = arr;
	_tmp16_ = json_array_get_elements (_tmp15_);
	{
		GList* node_collection = NULL;
		GList* node_it = NULL;
		node_collection = _tmp16_;
		for (node_it = node_collection; node_it != NULL; node_it = node_it->next) {
			JsonNode* node = NULL;
			node = (JsonNode*) node_it->data;
			{
				HyprWorkspace* _tmp17_;
				gint _tmp17__length1;
				gint _tmp18_;
				JsonNode* _tmp19_;
				JsonObject* _tmp20_;
				JsonNode* _tmp21_;
				JsonNode* _tmp22_;
				JsonObject* _tmp23_;
				JsonNode* _tmp24_;
				const gchar* _tmp25_;
				gchar* _tmp26_;
				JsonNode* _tmp27_;
				JsonObject* _tmp28_;
				JsonNode* _tmp29_;
				const gchar* _tmp30_;
				gchar* _tmp31_;
				JsonNode* _tmp32_;
				JsonObject* _tmp33_;
				JsonNode* _tmp34_;
				JsonNode* _tmp35_;
				JsonObject* _tmp36_;
				JsonNode* _tmp37_;
				JsonNode* _tmp38_;
				JsonObject* _tmp39_;
				JsonNode* _tmp40_;
				JsonNode* _tmp41_;
				JsonObject* _tmp42_;
				JsonNode* _tmp43_;
				const gchar* _tmp44_;
				gchar* _tmp45_;
				JsonNode* _tmp46_;
				JsonObject* _tmp47_;
				JsonNode* _tmp48_;
				const gchar* _tmp49_;
				gchar* _tmp50_;
				HyprWorkspace _tmp51_ = {0};
				_tmp17_ = self->workspaces;
				_tmp17__length1 = self->workspaces_length1;
				_tmp18_ = i;
				i = _tmp18_ + 1;
				_tmp19_ = node;
				_tmp20_ = json_node_get_object (_tmp19_);
				_tmp21_ = json_object_get_member (_tmp20_, "id");
				_tmp22_ = node;
				_tmp23_ = json_node_get_object (_tmp22_);
				_tmp24_ = json_object_get_member (_tmp23_, "name");
				_tmp25_ = json_node_get_string (_tmp24_);
				_tmp26_ = g_strdup (_tmp25_);
				_tmp27_ = node;
				_tmp28_ = json_node_get_object (_tmp27_);
				_tmp29_ = json_object_get_member (_tmp28_, "monitor");
				_tmp30_ = json_node_get_string (_tmp29_);
				_tmp31_ = g_strdup (_tmp30_);
				_tmp32_ = node;
				_tmp33_ = json_node_get_object (_tmp32_);
				_tmp34_ = json_object_get_member (_tmp33_, "monitorID");
				_tmp35_ = node;
				_tmp36_ = json_node_get_object (_tmp35_);
				_tmp37_ = json_object_get_member (_tmp36_, "windows");
				_tmp38_ = node;
				_tmp39_ = json_node_get_object (_tmp38_);
				_tmp40_ = json_object_get_member (_tmp39_, "hasfullscreen");
				_tmp41_ = node;
				_tmp42_ = json_node_get_object (_tmp41_);
				_tmp43_ = json_object_get_member (_tmp42_, "lastwindow");
				_tmp44_ = json_node_get_string (_tmp43_);
				_tmp45_ = g_strdup (_tmp44_);
				_tmp46_ = node;
				_tmp47_ = json_node_get_object (_tmp46_);
				_tmp48_ = json_object_get_member (_tmp47_, "lastwindowtitle");
				_tmp49_ = json_node_get_string (_tmp48_);
				_tmp50_ = g_strdup (_tmp49_);
				memset (&_tmp51_, 0, sizeof (HyprWorkspace));
				_tmp51_.id = json_node_get_int (_tmp21_);
				_g_free0 (_tmp51_.name);
				_tmp51_.name = _tmp26_;
				_g_free0 (_tmp51_.monitor);
				_tmp51_.monitor = _tmp31_;
				_tmp51_.monitorID = json_node_get_int (_tmp34_);
				_tmp51_.windows = json_node_get_int (_tmp37_);
				_tmp51_.hasfullscreen = json_node_get_boolean (_tmp40_);
				_g_free0 (_tmp51_.lastwindow);
				_tmp51_.lastwindow = _tmp45_;
				_g_free0 (_tmp51_.lastwindowtitle);
				_tmp51_.lastwindowtitle = _tmp50_;
				hypr_workspace_destroy (&_tmp17_[_tmp18_]);
				_tmp17_[_tmp18_] = _tmp51_;
			}
		}
		(node_collection == NULL) ? NULL : (node_collection = (g_list_free (node_collection), NULL));
	}
	_json_array_unref0 (arr);
	__vala_JsonNode_free0 (root);
	_g_object_unref0 (parser);
	_g_free0 (data);
	command = (_vala_array_free (command, command_length1, (GDestroyNotify) g_free), NULL);
}

static void
hyprland_set_current_workspace_clients (Hyprland* self)
{
	gint size = 0;
	HyprWindow* _tmp0_;
	gint _tmp0__length1;
	HyprWindow* _tmp6_;
	gint i = 0;
	HyprWindow* _tmp7_;
	gint _tmp7__length1;
	g_return_if_fail (self != NULL);
	size = 0;
	_tmp0_ = self->clients;
	_tmp0__length1 = self->clients_length1;
	{
		HyprWindow* win_collection = NULL;
		gint win_collection_length1 = 0;
		gint _win_collection_size_ = 0;
		gint win_it = 0;
		win_collection = _tmp0_;
		win_collection_length1 = _tmp0__length1;
		for (win_it = 0; win_it < win_collection_length1; win_it = win_it + 1) {
			HyprWindow _tmp1_;
			HyprWindow _tmp2_ = {0};
			HyprWindow win = {0};
			_tmp1_ = win_collection[win_it];
			hypr_window_copy (&_tmp1_, &_tmp2_);
			win = _tmp2_;
			{
				HyprWindow _tmp3_;
				HyprWorkspace _tmp4_;
				_tmp3_ = win;
				_tmp4_ = _tmp3_.workspace;
				if (_tmp4_.id == ((gint64) self->current_workspace_id)) {
					gint _tmp5_;
					_tmp5_ = size;
					size = _tmp5_ + 1;
				}
				hypr_window_destroy (&win);
			}
		}
	}
	_tmp6_ = g_new0 (HyprWindow, size);
	self->current_workspace_clients = (_vala_HyprWindow_array_free (self->current_workspace_clients, self->current_workspace_clients_length1), NULL);
	self->current_workspace_clients = _tmp6_;
	self->current_workspace_clients_length1 = size;
	i = 0;
	_tmp7_ = self->clients;
	_tmp7__length1 = self->clients_length1;
	{
		HyprWindow* win_collection = NULL;
		gint win_collection_length1 = 0;
		gint _win_collection_size_ = 0;
		gint win_it = 0;
		win_collection = _tmp7_;
		win_collection_length1 = _tmp7__length1;
		for (win_it = 0; win_it < win_collection_length1; win_it = win_it + 1) {
			HyprWindow _tmp8_;
			HyprWindow _tmp9_ = {0};
			HyprWindow win = {0};
			_tmp8_ = win_collection[win_it];
			hypr_window_copy (&_tmp8_, &_tmp9_);
			win = _tmp9_;
			{
				HyprWindow _tmp10_;
				HyprWorkspace _tmp11_;
				_tmp10_ = win;
				_tmp11_ = _tmp10_.workspace;
				if (_tmp11_.id == ((gint64) self->current_workspace_id)) {
					HyprWindow* _tmp12_;
					gint _tmp12__length1;
					gint _tmp13_;
					HyprWindow _tmp14_;
					HyprWindow _tmp15_;
					HyprWindow _tmp16_ = {0};
					_tmp12_ = self->current_workspace_clients;
					_tmp12__length1 = self->current_workspace_clients_length1;
					_tmp13_ = i;
					i = _tmp13_ + 1;
					_tmp14_ = win;
					_tmp15_ = _tmp14_;
					hypr_window_copy (&_tmp15_, &_tmp16_);
					hypr_window_destroy (&_tmp12_[_tmp13_]);
					_tmp12_[_tmp13_] = _tmp16_;
				}
				hypr_window_destroy (&win);
			}
		}
	}
}

static void
hyprland_set_actual_workspaces_len (Hyprland* self)
{
	gint64 max = 0LL;
	HyprWorkspace* _tmp0_;
	gint _tmp0__length1;
	g_return_if_fail (self != NULL);
	max = (gint64) 0;
	_tmp0_ = self->workspaces;
	_tmp0__length1 = self->workspaces_length1;
	{
		HyprWorkspace* ws_collection = NULL;
		gint ws_collection_length1 = 0;
		gint _ws_collection_size_ = 0;
		gint ws_it = 0;
		ws_collection = _tmp0_;
		ws_collection_length1 = _tmp0__length1;
		for (ws_it = 0; ws_it < ws_collection_length1; ws_it = ws_it + 1) {
			HyprWorkspace _tmp1_;
			HyprWorkspace _tmp2_ = {0};
			HyprWorkspace ws = {0};
			_tmp1_ = ws_collection[ws_it];
			hypr_workspace_copy (&_tmp1_, &_tmp2_);
			ws = _tmp2_;
			{
				HyprWorkspace _tmp3_;
				_tmp3_ = ws;
				if (_tmp3_.id > max) {
					HyprWorkspace _tmp4_;
					_tmp4_ = ws;
					max = _tmp4_.id;
				}
				hypr_workspace_destroy (&ws);
			}
		}
	}
	self->actual_workspace_len = (gint) max;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static gchar*
hyprland_read (Hyprland* self,
               gchar** command,
               gint command_length1)
{
	gchar* _tmp6_;
	GError* _inner_error0_ = NULL;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	{
		GSubprocess* process = NULL;
		GSubprocess* _tmp0_;
		GInputStream* inp = NULL;
		GInputStream* _tmp1_;
		GInputStream* _tmp2_;
		GInputStream* _tmp3_;
		gchar* _tmp4_;
		_tmp0_ = g_subprocess_newv (command, G_SUBPROCESS_FLAGS_STDOUT_PIPE, &_inner_error0_);
		process = _tmp0_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp1_ = g_subprocess_get_stdout_pipe (process);
		_tmp2_ = _g_object_ref0 (_tmp1_);
		inp = _tmp2_;
		_tmp3_ = inp;
		_tmp4_ = hyprland_read_all (self, _tmp3_);
		result = _tmp4_;
		_g_object_unref0 (inp);
		_g_object_unref0 (process);
		return result;
	}
	goto __finally0;
	__catch0_g_error:
	{
		FILE* _tmp5_;
		g_clear_error (&_inner_error0_);
		_tmp5_ = stdout;
		fprintf (_tmp5_, "GLib.Error occured");
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
	_tmp6_ = g_strdup ("");
	result = _tmp6_;
	return result;
}

static gchar*
hyprland_read_all (Hyprland* self,
                   GInputStream* inp)
{
	gchar* output = NULL;
	gchar* _tmp0_;
	guint8* r = NULL;
	gint r_length1 = 0;
	gint _r_size_ = 0;
	gint64 bytes_read = 0LL;
	GError* _inner_error0_ = NULL;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (inp != NULL, NULL);
	_tmp0_ = g_strdup ("");
	output = _tmp0_;
	bytes_read = (gint64) 0;
	{
		gboolean _tmp1_ = FALSE;
		_tmp1_ = TRUE;
		while (TRUE) {
			guint8* _tmp2_;
			guint8* _tmp3_;
			gint _tmp3__length1;
			gsize _tmp4_ = 0UL;
			const gchar* _tmp5_;
			guint8* _tmp6_;
			gint _tmp6__length1;
			gchar* _tmp7_;
			if (!_tmp1_) {
				if (!(bytes_read == ((gint64) 1024))) {
					break;
				}
			}
			_tmp1_ = FALSE;
			_tmp2_ = g_new0 (guint8, 1024);
			r = (g_free (r), NULL);
			r = _tmp2_;
			r_length1 = 1024;
			_r_size_ = r_length1;
			_tmp3_ = r;
			_tmp3__length1 = r_length1;
			g_input_stream_read_all (inp, _tmp3_, (gsize) _tmp3__length1, &_tmp4_, NULL, &_inner_error0_);
			bytes_read = (gint64) _tmp4_;
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				r = (g_free (r), NULL);
				_g_free0 (output);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
				g_clear_error (&_inner_error0_);
				return NULL;
			}
			_tmp5_ = output;
			_tmp6_ = r;
			_tmp6__length1 = r_length1;
			_tmp7_ = g_strconcat (_tmp5_, (const gchar*) _tmp6_, NULL);
			_g_free0 (output);
			output = _tmp7_;
		}
	}
	result = output;
	r = (g_free (r), NULL);
	return result;
}

gchar*
hyprland_dispatch_exec (Hyprland* self,
                        const gchar* command)
{
	gchar* cmd = NULL;
	gchar* _tmp0_;
	gchar** base_cmd = NULL;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar** _tmp5_;
	gint base_cmd_length1;
	gint _base_cmd_size_;
	gchar* _tmp6_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (command != NULL, NULL);
	_tmp0_ = g_strconcat ("$(", command, ")", NULL);
	cmd = _tmp0_;
	_tmp1_ = g_strdup ("hyprctl");
	_tmp2_ = g_strdup ("dispatch");
	_tmp3_ = g_strdup ("exec");
	_tmp4_ = g_strdup (cmd);
	_tmp5_ = g_new0 (gchar*, 4 + 1);
	_tmp5_[0] = _tmp1_;
	_tmp5_[1] = _tmp2_;
	_tmp5_[2] = _tmp3_;
	_tmp5_[3] = _tmp4_;
	base_cmd = _tmp5_;
	base_cmd_length1 = 4;
	_base_cmd_size_ = base_cmd_length1;
	_tmp6_ = hyprland_read (self, base_cmd, (gint) base_cmd_length1);
	result = _tmp6_;
	base_cmd = (_vala_array_free (base_cmd, base_cmd_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (cmd);
	return result;
}

void
hyprland_dispatch_workspace (Hyprland* self,
                             gint id)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar** _tmp4_;
	gchar** _tmp5_;
	gint _tmp5__length1;
	gchar* _tmp6_;
	gchar* _tmp7_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("hyprctl");
	_tmp1_ = g_strdup ("dispatch");
	_tmp2_ = g_strdup ("workspace");
	_tmp3_ = g_strdup_printf ("%i", id);
	_tmp4_ = g_new0 (gchar*, 4 + 1);
	_tmp4_[0] = _tmp0_;
	_tmp4_[1] = _tmp1_;
	_tmp4_[2] = _tmp2_;
	_tmp4_[3] = _tmp3_;
	_tmp5_ = _tmp4_;
	_tmp5__length1 = 4;
	_tmp6_ = hyprland_read (self, _tmp5_, (gint) 4);
	_tmp7_ = _tmp6_;
	_g_free0 (_tmp7_);
	_tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) g_free), NULL);
}

void
hyprland_get_activewindow (Hyprland* self,
                           HyprWindow * result)
{
	HyprWindow _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_activewindow;
	*result = _tmp0_;
	return;
}

static gboolean
_hypr_workspace_equal (const HyprWorkspace * s1,
                       const HyprWorkspace * s2)
{
	if (s1 == s2) {
		return TRUE;
	}
	if (s1 == NULL) {
		return FALSE;
	}
	if (s2 == NULL) {
		return FALSE;
	}
	if (s1->id != s2->id) {
		return FALSE;
	}
	if (g_strcmp0 (s1->name, s2->name)) {
		return FALSE;
	}
	if (g_strcmp0 (s1->monitor, s2->monitor)) {
		return FALSE;
	}
	if (s1->monitorID != s2->monitorID) {
		return FALSE;
	}
	if (s1->windows != s2->windows) {
		return FALSE;
	}
	if (s1->hasfullscreen != s2->hasfullscreen) {
		return FALSE;
	}
	if (g_strcmp0 (s1->lastwindow, s2->lastwindow)) {
		return FALSE;
	}
	if (g_strcmp0 (s1->lastwindowtitle, s2->lastwindowtitle)) {
		return FALSE;
	}
	return TRUE;
}

static gboolean
_hypr_window_equal (const HyprWindow * s1,
                    const HyprWindow * s2)
{
	if (s1 == s2) {
		return TRUE;
	}
	if (s1 == NULL) {
		return FALSE;
	}
	if (s2 == NULL) {
		return FALSE;
	}
	if (g_strcmp0 (s1->address, s2->address)) {
		return FALSE;
	}
	if (s1->mapped != s2->mapped) {
		return FALSE;
	}
	if (s1->hidden != s2->hidden) {
		return FALSE;
	}
	if (s1->at != s2->at) {
		return FALSE;
	}
	if (s1->size != s2->size) {
		return FALSE;
	}
	if (!_hypr_workspace_equal (&s1->workspace, &s2->workspace)) {
		return FALSE;
	}
	if (s1->floating != s2->floating) {
		return FALSE;
	}
	if (s1->pseudo != s2->pseudo) {
		return FALSE;
	}
	if (s1->monitor != s2->monitor) {
		return FALSE;
	}
	if (g_strcmp0 (s1->class, s2->class)) {
		return FALSE;
	}
	if (g_strcmp0 (s1->title, s2->title)) {
		return FALSE;
	}
	if (g_strcmp0 (s1->initialClass, s2->initialClass)) {
		return FALSE;
	}
	if (g_strcmp0 (s1->initialTitle, s2->initialTitle)) {
		return FALSE;
	}
	if (s1->pid != s2->pid) {
		return FALSE;
	}
	if (s1->xwayland != s2->xwayland) {
		return FALSE;
	}
	if (s1->pinned != s2->pinned) {
		return FALSE;
	}
	if (s1->fullscreen != s2->fullscreen) {
		return FALSE;
	}
	if (s1->fullscreenClient != s2->fullscreenClient) {
		return FALSE;
	}
	if (s1->grouped != s2->grouped) {
		return FALSE;
	}
	if (s1->tags != s2->tags) {
		return FALSE;
	}
	if (g_strcmp0 (s1->swallowing, s2->swallowing)) {
		return FALSE;
	}
	if (s1->focusHistoryID != s2->focusHistoryID) {
		return FALSE;
	}
	return TRUE;
}

static void
hyprland_set_activewindow (Hyprland* self,
                           HyprWindow * value)
{
	HyprWindow old_value;
	g_return_if_fail (self != NULL);
	hyprland_get_activewindow (self, &old_value);
	if (_hypr_window_equal (value, &old_value) != TRUE) {
		HyprWindow _tmp0_;
		HyprWindow _tmp1_;
		HyprWindow _tmp2_ = {0};
		_tmp0_ = *value;
		_tmp1_ = _tmp0_;
		hypr_window_copy (&_tmp1_, &_tmp2_);
		hypr_window_destroy (&self->priv->_activewindow);
		self->priv->_activewindow = _tmp2_;
		g_object_notify_by_pspec ((GObject *) self, hyprland_properties[HYPRLAND_ACTIVEWINDOW_PROPERTY]);
	}
}

static void
g_cclosure_user_marshal_VOID__POINTER_INT (GClosure * closure,
                                           GValue * return_value,
                                           guint n_param_values,
                                           const GValue * param_values,
                                           gpointer invocation_hint,
                                           gpointer marshal_data)
{
	typedef void (*GMarshalFunc_VOID__POINTER_INT) (gpointer data1, gpointer arg_1, gint arg_2, gpointer data2);
	register GMarshalFunc_VOID__POINTER_INT callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__POINTER_INT) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_pointer (param_values + 1), g_value_get_int (param_values + 2), data2);
}

static void
hyprland_class_init (HyprlandClass * klass,
                     gpointer klass_data)
{
	hyprland_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &Hyprland_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_hyprland_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_hyprland_set_property;
	G_OBJECT_CLASS (klass)->finalize = hyprland_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), HYPRLAND_ACTIVEWINDOW_PROPERTY, hyprland_properties[HYPRLAND_ACTIVEWINDOW_PROPERTY] = g_param_spec_boxed ("activewindow", "activewindow", "activewindow", HYPR_TYPE_WINDOW, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	hyprland_signals[HYPRLAND_SIG_CHANGE_SIGNAL] = g_signal_new ("sig-change", TYPE_HYPRLAND, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	hyprland_signals[HYPRLAND_SIG_ACTIVEWINDOW_SIGNAL] = g_signal_new ("sig-activewindow", TYPE_HYPRLAND, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOXED, G_TYPE_NONE, 1, HYPR_TYPE_WINDOW);
	hyprland_signals[HYPRLAND_SIG_WORKSPACES_SIGNAL] = g_signal_new ("sig-workspaces", TYPE_HYPRLAND, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__POINTER_INT, G_TYPE_NONE, 2, G_TYPE_POINTER, G_TYPE_INT);
	hyprland_signals[HYPRLAND_SIG_CLIENTS_SIGNAL] = g_signal_new ("sig-clients", TYPE_HYPRLAND, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__POINTER_INT, G_TYPE_NONE, 2, G_TYPE_POINTER, G_TYPE_INT);
	hyprland_signals[HYPRLAND_SIG_CURRENT_WORKSPACE_CLIENTS_SIGNAL] = g_signal_new ("sig-current-workspace-clients", TYPE_HYPRLAND, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__POINTER_INT, G_TYPE_NONE, 2, G_TYPE_POINTER, G_TYPE_INT);
}

static void
hyprland_instance_init (Hyprland * self,
                        gpointer klass)
{
	self->priv = hyprland_get_instance_private (self);
	self->current_workspace_id = 1;
	self->actual_workspace_len = 1;
}

static void
hyprland_finalize (GObject * obj)
{
	Hyprland * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_HYPRLAND, Hyprland);
	hypr_window_destroy (&self->priv->_activewindow);
	self->workspaces = (_vala_HyprWorkspace_array_free (self->workspaces, self->workspaces_length1), NULL);
	self->clients = (_vala_HyprWindow_array_free (self->clients, self->clients_length1), NULL);
	self->current_workspace_clients = (_vala_HyprWindow_array_free (self->current_workspace_clients, self->current_workspace_clients_length1), NULL);
	G_OBJECT_CLASS (hyprland_parent_class)->finalize (obj);
}

static GType
hyprland_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (HyprlandClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) hyprland_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Hyprland), 0, (GInstanceInitFunc) hyprland_instance_init, NULL };
	GType hyprland_type_id;
	hyprland_type_id = g_type_register_static (G_TYPE_OBJECT, "Hyprland", &g_define_type_info, 0);
	Hyprland_private_offset = g_type_add_instance_private (hyprland_type_id, sizeof (HyprlandPrivate));
	return hyprland_type_id;
}

GType
hyprland_get_type (void)
{
	static volatile gsize hyprland_type_id__once = 0;
	if (g_once_init_enter (&hyprland_type_id__once)) {
		GType hyprland_type_id;
		hyprland_type_id = hyprland_get_type_once ();
		g_once_init_leave (&hyprland_type_id__once, hyprland_type_id);
	}
	return hyprland_type_id__once;
}

static void
_vala_hyprland_get_property (GObject * object,
                             guint property_id,
                             GValue * value,
                             GParamSpec * pspec)
{
	Hyprland * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_HYPRLAND, Hyprland);
	switch (property_id) {
		case HYPRLAND_ACTIVEWINDOW_PROPERTY:
		{
			HyprWindow boxed;
			hyprland_get_activewindow (self, &boxed);
			g_value_set_boxed (value, &boxed);
		}
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_hyprland_set_property (GObject * object,
                             guint property_id,
                             const GValue * value,
                             GParamSpec * pspec)
{
	Hyprland * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_HYPRLAND, Hyprland);
	switch (property_id) {
		case HYPRLAND_ACTIVEWINDOW_PROPERTY:
		hyprland_set_activewindow (self, g_value_get_boxed (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
	if (mem && byte_size != 0) {
		new_mem = g_malloc (byte_size);
		memcpy (new_mem, mem, byte_size);
	} else {
		new_mem = NULL;
	}
	return new_mem;
}

