/* Upower.h generated by valac 0.56.16, the Vala compiler, do not modify */

#ifndef ___HOME_EM_DESKTOP_CODE_DOCKS_SERVICES_LIBS_UPOWER_H__
#define ___HOME_EM_DESKTOP_CODE_DOCKS_SERVICES_LIBS_UPOWER_H__

#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_UPOWER (upower_get_type ())
#define UPOWER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_UPOWER, Upower))
#define UPOWER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_UPOWER, UpowerClass))
#define IS_UPOWER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_UPOWER))
#define IS_UPOWER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_UPOWER))
#define UPOWER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_UPOWER, UpowerClass))

typedef struct _Upower Upower;
typedef struct _UpowerClass UpowerClass;
typedef struct _UpowerPrivate UpowerPrivate;

struct _Upower {
	GObject parent_instance;
	UpowerPrivate * priv;
};

struct _UpowerClass {
	GObjectClass parent_class;
};

VALA_EXTERN GType upower_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Upower, g_object_unref)
VALA_EXTERN void upower_start (Upower* self);
VALA_EXTERN Upower* upower_new (void);
VALA_EXTERN Upower* upower_construct (GType object_type);
VALA_EXTERN gint upower_get_battery_level (Upower* self);
VALA_EXTERN const gchar* upower_get_state (Upower* self);
VALA_EXTERN const gchar* upower_get_time_remaining (Upower* self);
VALA_EXTERN const gchar* upower_get_icon_name (Upower* self);

G_END_DECLS

#endif
